-- Extremely Attractive Mock Data Insertion
DO $$
DECLARE
  u0 UUID;
  u1 UUID;
  u2 UUID;
  u3 UUID;
  u4 UUID;
  u5 UUID;
  u6 UUID;
  u7 UUID;
BEGIN
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='hotmock0@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'hotmock0@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u0 FROM auth.users WHERE email='hotmock0@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='hotmock1@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'hotmock1@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u1 FROM auth.users WHERE email='hotmock1@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='hotmock2@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'hotmock2@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u2 FROM auth.users WHERE email='hotmock2@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='hotmock3@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'hotmock3@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u3 FROM auth.users WHERE email='hotmock3@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='hotmock4@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'hotmock4@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u4 FROM auth.users WHERE email='hotmock4@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='hotmock5@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'hotmock5@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u5 FROM auth.users WHERE email='hotmock5@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='hotmock6@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'hotmock6@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u6 FROM auth.users WHERE email='hotmock6@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='hotmock7@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'hotmock7@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u7 FROM auth.users WHERE email='hotmock7@migo.app' LIMIT 1;
  INSERT INTO profiles(id,name,email,bio,age,gender,nationality,location,lat,lng,languages,interests,mbti,verified,plan,photo_url,photo_urls) VALUES(u0,'시아', 'hotmock0@migo.app', '오늘 저녁 한강에서 맥주 한잔 어때요? 🌙 혼자라서 심심해요..', 24,'여성','대한민국','서울특별시, 대한민국',37.541,127.07,ARRAY['한국어','English'], ARRAY['여행','카페','맛집'], 'ENFP', true, 'premium', 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80']) ON CONFLICT (id) DO UPDATE SET photo_url='https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80', bio='오늘 저녁 한강에서 맥주 한잔 어때요? 🌙 혼자라서 심심해요..', lat=37.541, lng=127.07;
  INSERT INTO profiles(id,name,email,bio,age,gender,nationality,location,lat,lng,languages,interests,mbti,verified,plan,photo_url,photo_urls) VALUES(u1,'Chloe', 'hotmock1@migo.app', 'Looking for a spontaneous trip partner! ✈️ First round is on me 🥂', 26,'여성','대한민국','서울특별시, 대한민국',37.545,127.075,ARRAY['한국어','English'], ARRAY['여행','카페','맛집'], 'ESTP', true, 'premium', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80']) ON CONFLICT (id) DO UPDATE SET photo_url='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80', bio='Looking for a spontaneous trip partner! ✈️ First round is on me 🥂', lat=37.545, lng=127.075;
  INSERT INTO profiles(id,name,email,bio,age,gender,nationality,location,lat,lng,languages,interests,mbti,verified,plan,photo_url,photo_urls) VALUES(u2,'수진', 'hotmock2@migo.app', '요즘 날씨 너무 좋지 않아요? 같이 예쁜 카페 갈 사람 찾아요 ☕️ 디저트는 제가 쏠게요!', 25,'여성','대한민국','서울특별시, 대한민국',37.55,127.08,ARRAY['한국어','English'], ARRAY['여행','카페','맛집'], 'ISFP', true, 'premium', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80']) ON CONFLICT (id) DO UPDATE SET photo_url='https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80', bio='요즘 날씨 너무 좋지 않아요? 같이 예쁜 카페 갈 사람 찾아요 ☕️ 디저트는 제가 쏠게요!', lat=37.55, lng=127.08;
  INSERT INTO profiles(id,name,email,bio,age,gender,nationality,location,lat,lng,languages,interests,mbti,verified,plan,photo_url,photo_urls) VALUES(u3,'엘레나', 'hotmock3@migo.app', '주말에 드라이브 가고 싶은데 면허가 없어요🥺 운전 잘하시는 분? 뷰 좋은 곳 가요!', 27,'여성','대한민국','서울특별시, 대한민국',37.548,127.073,ARRAY['한국어','English'], ARRAY['여행','카페','맛집'], 'ENFJ', true, 'premium', 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80']) ON CONFLICT (id) DO UPDATE SET photo_url='https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80', bio='주말에 드라이브 가고 싶은데 면허가 없어요🥺 운전 잘하시는 분? 뷰 좋은 곳 가요!', lat=37.548, lng=127.073;
  INSERT INTO profiles(id,name,email,bio,age,gender,nationality,location,lat,lng,languages,interests,mbti,verified,plan,photo_url,photo_urls) VALUES(u4,'유리', 'hotmock4@migo.app', '맛난거 먹으면서 수다 떠는게 젤 좋아요🥰 저랑 맛집 도장깨기 하실 분 구함!', 23,'여성','대한민국','서울특별시, 대한민국',37.542,127.078,ARRAY['한국어','English'], ARRAY['여행','카페','맛집'], 'ESFJ', true, 'premium', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80']) ON CONFLICT (id) DO UPDATE SET photo_url='https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80', bio='맛난거 먹으면서 수다 떠는게 젤 좋아요🥰 저랑 맛집 도장깨기 하실 분 구함!', lat=37.542, lng=127.078;
  INSERT INTO profiles(id,name,email,bio,age,gender,nationality,location,lat,lng,languages,interests,mbti,verified,plan,photo_url,photo_urls) VALUES(u5,'태현', 'hotmock5@migo.app', '차박이랑 캠핑 좋아합니다. 몸만 오시면 다 준비해드려요 🏕 힐링하러 갈 사람?', 28,'남성','대한민국','서울특별시, 대한민국',37.543,127.071,ARRAY['한국어','English'], ARRAY['여행','카페','맛집'], 'ENTJ', true, 'premium', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80']) ON CONFLICT (id) DO UPDATE SET photo_url='https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80', bio='차박이랑 캠핑 좋아합니다. 몸만 오시면 다 준비해드려요 🏕 힐링하러 갈 사람?', lat=37.543, lng=127.071;
  INSERT INTO profiles(id,name,email,bio,age,gender,nationality,location,lat,lng,languages,interests,mbti,verified,plan,photo_url,photo_urls) VALUES(u6,'Kevin', 'hotmock6@migo.app', '운동 좋아하고 맛집 찾아다니는거 좋아해요 💪 같이 바디프로필 찍을 파트너 환영!', 30,'남성','대한민국','서울특별시, 대한민국',37.549,127.077,ARRAY['한국어','English'], ARRAY['여행','카페','맛집'], 'ESTJ', true, 'premium', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80']) ON CONFLICT (id) DO UPDATE SET photo_url='https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', bio='운동 좋아하고 맛집 찾아다니는거 좋아해요 💪 같이 바디프로필 찍을 파트너 환영!', lat=37.549, lng=127.077;
  INSERT INTO profiles(id,name,email,bio,age,gender,nationality,location,lat,lng,languages,interests,mbti,verified,plan,photo_url,photo_urls) VALUES(u7,'지훈', 'hotmock7@migo.app', '와인 한잔의 여유를 아는 분🍷 맛있는 음식과 좋은 음악, 그리고 깊은 대화 나눠요', 29,'남성','대한민국','서울특별시, 대한민국',37.547,127.074,ARRAY['한국어','English'], ARRAY['여행','카페','맛집'], 'INFJ', true, 'premium', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80']) ON CONFLICT (id) DO UPDATE SET photo_url='https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80', bio='와인 한잔의 여유를 아는 분🍷 맛있는 음식과 좋은 음악, 그리고 깊은 대화 나눠요', lat=37.547, lng=127.074;
  -- DELETE OLD ATTRACTIVE POSTS SO WE DON'T CLUTTER
  DELETE FROM posts WHERE content LIKE '%같이 시간 보낼 분 구해요!%';
  INSERT INTO posts(id, author_id, title, content, image_url, image_urls, created_at) VALUES (gen_random_uuid(), u0, '같이 시간 보낼 분 구해요!', '이번 주말에 갑자기 바다가 너무 보고싶은데 같이 훌쩍 떠나실 분 있나요? 차는 제가 렌트할게요 🚗 낭만을 아시는 분이었으면 좋겠네요!', 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80'], NOW() - INTERVAL '0 hours');
  INSERT INTO posts(id, author_id, title, content, image_url, image_urls, created_at) VALUES (gen_random_uuid(), u1, '같이 시간 보낼 분 구해요!', '요즘 운동 시작했는데 혼자 하니까 의지가 꺾여요 ㅠㅠ 운동 끝나고 같이 샐러드나 치팅데이 메뉴 먹을 운동메이트 구해요!! 🏋️‍♀️✨', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80'], NOW() - INTERVAL '1 hours');
  INSERT INTO posts(id, author_id, title, content, image_url, image_urls, created_at) VALUES (gen_random_uuid(), u2, '같이 시간 보낼 분 구해요!', '방금 엄청 분위기 좋은 스피크이지 바를 찾았는데 혼자 가기엔 좀 아쉬워요 칵테일 한잔 하면서 진솔한 얘기 나눌 사람 계신가요? 🍸', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80'], NOW() - INTERVAL '2 hours');
  INSERT INTO posts(id, author_id, title, content, image_url, image_urls, created_at) VALUES (gen_random_uuid(), u3, '같이 시간 보낼 분 구해요!', '집에만 있기 너무 아까운 날씨네요 ☀️ 근처 공원에서 돗자리 펴고 피맥할 사람? 제가 피자는 시킬게요 맥주만 사서 오세요! 🍕🍻', 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80'], NOW() - INTERVAL '3 hours');
  INSERT INTO posts(id, author_id, title, content, image_url, image_urls, created_at) VALUES (gen_random_uuid(), u4, '같이 시간 보낼 분 구해요!', '다음달에 도쿄 가려고 비행기표 질렀는데 일정 하나도 안짰어요 ㅋㅋㅋ J 성향이신 분 저 좀 구제해주세요 같이 가요!! 🇯🇵', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80'], NOW() - INTERVAL '4 hours');
END $$;