-- International Attractive Mock Data Insertion
DO $$
DECLARE
  u0 UUID; u1 UUID; u2 UUID; u3 UUID; u4 UUID;
  u5 UUID; u6 UUID; u7 UUID; u8 UUID; u9 UUID;
BEGIN
  -- Insert Auth Users
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='intl_mock0@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'intl_mock0@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u0 FROM auth.users WHERE email='intl_mock0@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='intl_mock1@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'intl_mock1@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u1 FROM auth.users WHERE email='intl_mock1@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='intl_mock2@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'intl_mock2@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u2 FROM auth.users WHERE email='intl_mock2@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='intl_mock3@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'intl_mock3@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u3 FROM auth.users WHERE email='intl_mock3@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='intl_mock4@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'intl_mock4@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u4 FROM auth.users WHERE email='intl_mock4@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='intl_mock5@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'intl_mock5@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u5 FROM auth.users WHERE email='intl_mock5@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='intl_mock6@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'intl_mock6@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u6 FROM auth.users WHERE email='intl_mock6@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='intl_mock7@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'intl_mock7@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u7 FROM auth.users WHERE email='intl_mock7@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='intl_mock8@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'intl_mock8@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u8 FROM auth.users WHERE email='intl_mock8@migo.app' LIMIT 1;
  IF NOT EXISTS(SELECT 1 FROM auth.users WHERE email='intl_mock9@migo.app') THEN INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data,aud,role,is_super_admin) VALUES(gen_random_uuid(),'intl_mock9@migo.app','',NOW(),NOW(),NOW(),'{"provider":"email","providers":["email"]}','{}','authenticated','authenticated',false); END IF;
  SELECT id INTO u9 FROM auth.users WHERE email='intl_mock9@migo.app' LIMIT 1;

  -- Delete existing to avoid clutter if re-run
  DELETE FROM profiles WHERE email LIKE 'intl_mock%@migo.app';
  DELETE FROM posts WHERE content LIKE '%📍 Seoul Visitor%';

  -- Insert Profiles 
  INSERT INTO profiles(id, name, email, bio, age, gender, nationality, location, lat, lng, languages, interests, mbti, verified, plan, photo_url, photo_urls) VALUES
  (u0, 'Aiko', 'intl_mock0@migo.app', 'こんにちは！美味しいコーヒーと綺麗な景色が好きです。一緒にカフェ巡りしませんか？☕️✨', 24, '여성', '🇯🇵 일본', '서울특별시, 대한민국', 37.5410, 127.0700, ARRAY['日本語', 'English'], ARRAY['카페', '사진', '예술'], 'ISFP', true, 'premium', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80']),
  (u1, 'Camille', 'intl_mock1@migo.app', 'Salut! J''adore découvrir de nouveaux endroits et déguster du bon vin. On va boire un verre ce soir ? 🍷✨', 26, '여성', '🇫🇷 프랑스', '서울특별시, 대한민국', 37.5450, 127.0750, ARRAY['Français', 'English'], ARRAY['와인', '미식', '파티'], 'ENFJ', true, 'premium', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80']),
  (u2, 'Jessica', 'intl_mock2@migo.app', 'Hey there! Just visiting for a few weeks. Looking for someone to show me around the city! First drink is on me 🥂', 25, '여성', '🇺🇸 미국', '서울특별시, 대한민국', 37.5500, 127.0800, ARRAY['English'], ARRAY['여행', '음악', '파티'], 'ESTP', true, 'premium', 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80']),
  (u3, 'Isabella', 'intl_mock3@migo.app', '¡Hola! Busco a alguien que me enseñe los mejores restaurantes de la ciudad. ¡Me encanta la comida picante! 🌮🌶️', 27, '여성', '🇪🇸 스페인', '서울특별시, 대한민국', 37.5480, 127.0730, ARRAY['Español', 'English'], ARRAY['맛집', '산책', '문화'], 'ESFP', true, 'premium', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80']),
  (u4, 'Valentina', 'intl_mock4@migo.app', 'Oie! Sou apaixonada por dança e praia. Alguém afim de sair pra curtir a noite e dançar muito? 🏖️🍹', 23, '여성', '🇧🇷 브라질', '서울특별시, 대한민국', 37.5420, 127.0780, ARRAY['Português', 'English'], ARRAY['댄스', '파티', '음악'], 'ENFP', true, 'premium', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80']),
  (u5, 'Oliver', 'intl_mock5@migo.app', 'Hello mate! Love a good pint and watching football. Anyone up for a pub crawl tonight? 🍻⚽️', 28, '남성', '🇬🇧 영국', '서울특별시, 대한민국', 37.5430, 127.0710, ARRAY['English'], ARRAY['축구', '맥주', '아웃도어'], 'ESTP', true, 'premium', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80']),
  (u6, 'Lukas', 'intl_mock6@migo.app', 'Hallo! Ich reise gerne und liebe es, neue Kulturen kennenzulernen. Lass uns ein Bier trinken gehen! 🍺', 29, '남성', '🇩🇪 독일', '서울특별시, 대한민국', 37.5490, 127.0770, ARRAY['Deutsch', 'English'], ARRAY['여행', '독서', '역사'], 'INTJ', true, 'premium', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80']),
  (u7, 'Kenji', 'intl_mock7@migo.app', 'はじめまして！カメラマンをしてます。もしよかったらポートレート撮らせてください📸', 27, '남성', '🇯🇵 일본', '서울특별시, 대한민국', 37.5470, 127.0740, ARRAY['日本語', 'English'], ARRAY['사진', '예술', '영화'], 'INFP', true, 'premium', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80']),
  (u8, 'Lucas', 'intl_mock8@migo.app', 'Bonjour ! J''aime l''art, la musique et les longues promenades. Tu viens avec moi ? 🎨🎶', 30, '남성', '🇫🇷 프랑스', '서울특별시, 대한민국', 37.5510, 127.0790, ARRAY['Français', 'English'], ARRAY['음악', '미술관', '요리'], 'INFJ', true, 'premium', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80']),
  (u9, 'Giulia', 'intl_mock9@migo.app', 'Ciao! Cerco qualcuno con cui esplorare la città e magari mangiare una buona pizza. 🍕❤️', 25, '여성', '🇮🇹 이탈리아', '서울특별시, 대한민국', 37.5440, 127.0760, ARRAY['Italiano', 'English'], ARRAY['요리', '카페', '패션'], 'ENFP', true, 'premium', 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=800&q=80']);

  -- Insert Community Posts
  INSERT INTO posts(id, author_id, title, content, image_url, image_urls, created_at) VALUES 
  (gen_random_uuid(), u0, '📍 Seoul Visitor', '日本から遊びに来ました！一緒に韓国の美味しいカフェに行きませんか？ 😊', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80'], NOW() - INTERVAL '1 hours'),
  (gen_random_uuid(), u2, '📍 Seoul Visitor', 'Hey guys! Looking for some recommendations for nightlife in Seoul! Or better yet, come with me? 🍸✨', 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80'], NOW() - INTERVAL '2 hours'),
  (gen_random_uuid(), u3, '📍 Seoul Visitor', '¿Alguien quiere ir a probar comida coreana callejera hoy por la noche? 🍡🥟 Estoy emocionada!', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80'], NOW() - INTERVAL '3 hours'),
  (gen_random_uuid(), u8, '📍 Seoul Visitor', 'Je cherche de bons restaurants à Séoul. Si quelqu''un veut se joindre à moi, faites-moi signe ! 🍷', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80', ARRAY['https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&q=80'], NOW() - INTERVAL '4 hours');

END $$;
