// add_filter_langs3.cjs - final batch
const fs = require('fs');
const fp = 'src/i18n/filterLocales.ts';
let c = fs.readFileSync(fp, 'utf8').trimEnd();
if (!c.endsWith('};')) { console.error('Unexpected ending'); process.exit(1); }

const langs = {
  cs: {
    gf: { c_tokyo:'Tokio',c_seoul:'Soul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapur',c_osaka:'Osaka',c_taipei:'Taipei',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Paříž',n_jp:'Japonsko',n_kr:'Korea',n_th:'Thajsko',n_id:'Indonésie',n_vn:'Vietnam',n_sg:'Singapur',n_tw:'Tchaj-wan',n_ph:'Filipíny',n_es:'Španělsko',n_fr:'Francie',s_2:'2 os.',s_3:'3 os.',s_4:'4 os.',s_5:'5 os.',s_6:'6 os.',w_sun:'Ne',w_mon:'Po',w_tue:'Út',w_wed:'St',w_thu:'Čt',w_fri:'Pá',w_sat:'So',m_1:'Led',m_2:'Úno',m_3:'Bře',m_4:'Dub',m_5:'Kvě',m_6:'Čvn',m_7:'Čvc',m_8:'Srp',m_9:'Zář',m_10:'Říj',m_11:'Lis',m_12:'Pro',p_we:'Tento víkend',p_nw:'Příští týden',p_tm:'Tento měsíc',p_nm:'Příští měsíc',title:'Filtry cesty',desc:'Nastavte kritéria pro spolucestujícího.',reset:'Resetovat',dest:'Cíl',dest_ph:'Hledat město...',search_res:'Výsledky',pop_city:'Oblíbená města',apply_as_is:' Hledat',date:'Datum',sel_start:'Odjezd',sel_end:'Návrat',year:' ',month:' ',day:'',size:'Počet osob',all:'Nezáleží',s_6_more:'6+',unit_p:' os.',apply:'Použít ',unit_f:'',view_all:'Všechny skupiny' },
    gdf: { activity:'Aktivita',tour:'Výlet',food:'Restaurace',cafe:'Kavárna',club:'Klub',any:'Vše',gender:'Složení',g_2m2f:'2M2Ž',g_3m1f:'3M1Ž',g_1m3f:'1M3Ž',g_all_m:'Jen muži',g_all_f:'Jen ženy',lang:'Jazyk',l_any:'Nezáleží',l_any_desc:'Všechny jazyky',l_ko:'Korejsky',l_ko_desc:'Hlavně korejsky',l_for:'Cizí',l_for_desc:'Anglicky/cizí',l_mix:'Smíšeně',l_mix_desc:'Mezinárodní',vibe:'Atmosféra',v_any_desc:'Jakákoliv',v_cas:'Uvolněná',v_cas_desc:'Casual',v_party:'Párty',v_party_desc:'Párty!',v_ser:'Vážná',v_ser_desc:'Cílevědomá',title:'Filtry skupiny',desc:'Nastavte kritéria.',reset:'Resetovat',chk:'Také se přihlásit',cur:'Skupiny v ',based:'',apply:'Použít ',unit:'',all:'Všechny skupiny' }
  },
  ro: {
    gf: { c_tokyo:'Tokyo',c_seoul:'Seul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapore',c_osaka:'Osaka',c_taipei:'Taipei',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Paris',n_jp:'Japonia',n_kr:'Coreea',n_th:'Thailanda',n_id:'Indonezia',n_vn:'Vietnam',n_sg:'Singapore',n_tw:'Taiwan',n_ph:'Filipine',n_es:'Spania',n_fr:'Franța',s_2:'2 pers.',s_3:'3 pers.',s_4:'4 pers.',s_5:'5 pers.',s_6:'6 pers.',w_sun:'Du',w_mon:'Lu',w_tue:'Ma',w_wed:'Mi',w_thu:'Jo',w_fri:'Vi',w_sat:'Sâ',m_1:'Ian',m_2:'Feb',m_3:'Mar',m_4:'Apr',m_5:'Mai',m_6:'Iun',m_7:'Iul',m_8:'Aug',m_9:'Sep',m_10:'Oct',m_11:'Nov',m_12:'Dec',p_we:'Acest weekend',p_nw:'Săptămâna viitoare',p_tm:'Luna aceasta',p_nm:'Luna viitoare',title:'Filtre călătorie',desc:'Setați criteriile însoțitorului.',reset:'Resetare',dest:'Destinație',dest_ph:'Caută oraș...',search_res:'Rezultate',pop_city:'Orașe populare',apply_as_is:' Caută',date:'Dată',sel_start:'Plecare',sel_end:'Întoarcere',year:' ',month:' ',day:'',size:'Număr persoane',all:'Nu contează',s_6_more:'6+',unit_p:' pers.',apply:'Aplică ',unit_f:'',view_all:'Toate grupurile' },
    gdf: { activity:'Activitate',tour:'Tur',food:'Restaurant',cafe:'Cafea',club:'Club',any:'Toate',gender:'Componență',g_2m2f:'2B2F',g_3m1f:'3B1F',g_1m3f:'1B3F',g_all_m:'Numai bărbați',g_all_f:'Numai femei',lang:'Limbă',l_any:'Nu contează',l_any_desc:'Toate limbile',l_ko:'Coreeană',l_ko_desc:'Preponderent coreeană',l_for:'Străin',l_for_desc:'Engleză/Străin',l_mix:'Mixt',l_mix_desc:'Multinațional',vibe:'Atmosferă',v_any_desc:'Orice atmosferă',v_cas:'Relaxat',v_cas_desc:'Casual',v_party:'Petrecere',v_party_desc:'Petrecere!',v_ser:'Serios',v_ser_desc:'Cu scop',title:'Filtre grup',desc:'Setați criteriile.',reset:'Resetare',chk:'Check-in și',cur:'Grupuri în ',based:'',apply:'Aplică ',unit:'',all:'Toate grupurile' }
  },
  hu: {
    gf: { c_tokyo:'Tokió',c_seoul:'Szöul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Szingapúr',c_osaka:'Oszaka',c_taipei:'Tajpej',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Párizs',n_jp:'Japán',n_kr:'Korea',n_th:'Thaiföld',n_id:'Indonézia',n_vn:'Vietnam',n_sg:'Szingapúr',n_tw:'Tajvan',n_ph:'Fülöp-szigetek',n_es:'Spanyolország',n_fr:'Franciaország',s_2:'2 fő',s_3:'3 fő',s_4:'4 fő',s_5:'5 fő',s_6:'6 fő',w_sun:'V',w_mon:'H',w_tue:'K',w_wed:'Sz',w_thu:'Cs',w_fri:'P',w_sat:'Sz',m_1:'Jan',m_2:'Feb',m_3:'Már',m_4:'Ápr',m_5:'Máj',m_6:'Jún',m_7:'Júl',m_8:'Aug',m_9:'Sze',m_10:'Okt',m_11:'Nov',m_12:'Dec',p_we:'Ezen a hétvégén',p_nw:'Jövő héten',p_tm:'Ebben a hónapban',p_nm:'Jövő hónapban',title:'Utazási szűrők',desc:'Állítsd be a társ kritériumait.',reset:'Visszaállítás',dest:'Úticél',dest_ph:'Keress várost...',search_res:'Eredmények',pop_city:'Népszerű városok',apply_as_is:' Keresés',date:'Dátum',sel_start:'Indulás',sel_end:'Visszaérkezés',year:' ',month:' ',day:'',size:'Személyek száma',all:'Nem számít',s_6_more:'6+',unit_p:' fő',apply:'Alkalmaz ',unit_f:'',view_all:'Összes csoport' },
    gdf: { activity:'Tevékenység',tour:'Kirándulás',food:'Étterem',cafe:'Kávézó',club:'Klub',any:'Mind',gender:'Összetétel',g_2m2f:'2F2N',g_3m1f:'3F1N',g_1m3f:'1F3N',g_all_m:'Csak férfiak',g_all_f:'Csak nők',lang:'Nyelv',l_any:'Nem számít',l_any_desc:'Minden nyelv',l_ko:'Koreai',l_ko_desc:'Főleg koreai',l_for:'Külföldi',l_for_desc:'Angol/külföldi',l_mix:'Vegyes',l_mix_desc:'Multinacionális',vibe:'Hangulat',v_any_desc:'Bármilyen hangulat',v_cas:'Laza',v_cas_desc:'Casual',v_party:'Buli',v_party_desc:'Buli!',v_ser:'Komoly',v_ser_desc:'Céltudatos',title:'Csoportszűrők',desc:'Állítsd be a kritériumokat.',reset:'Visszaállítás',chk:'Bejelentkezés is',cur:'Csoportok: ',based:'',apply:'Alkalmaz ',unit:'',all:'Összes csoport' }
  },
  el: {
    gf: { c_tokyo:'Τόκιο',c_seoul:'Σεούλ',c_bangkok:'Μπανγκόκ',c_bali:'Μπαλί',c_danang:'Ντα Νανγκ',c_sg:'Σιγκαπούρη',c_osaka:'Οσάκα',c_taipei:'Ταϊπέι',c_chiangmai:'Τσιάνγκ Μάι',c_cebu:'Σεμπού',c_bcn:'Βαρκελώνη',c_paris:'Παρίσι',n_jp:'Ιαπωνία',n_kr:'Κορέα',n_th:'Ταϊλάνδη',n_id:'Ινδονησία',n_vn:'Βιετνάμ',n_sg:'Σιγκαπούρη',n_tw:'Ταϊβάν',n_ph:'Φιλιππίνες',n_es:'Ισπανία',n_fr:'Γαλλία',s_2:'2 άτ.',s_3:'3 άτ.',s_4:'4 άτ.',s_5:'5 άτ.',s_6:'6 άτ.',w_sun:'Κυρ',w_mon:'Δευ',w_tue:'Τρί',w_wed:'Τετ',w_thu:'Πέμ',w_fri:'Παρ',w_sat:'Σάβ',m_1:'Ιαν',m_2:'Φεβ',m_3:'Μαρ',m_4:'Απρ',m_5:'Μαΐ',m_6:'Ιουν',m_7:'Ιουλ',m_8:'Αυγ',m_9:'Σεπ',m_10:'Οκτ',m_11:'Νοε',m_12:'Δεκ',p_we:'Αυτό το Σαββατοκύριακο',p_nw:'Την επόμενη εβδομάδα',p_tm:'Αυτό τον μήνα',p_nm:'Τον επόμενο μήνα',title:'Φίλτρα ταξιδιού',desc:'Ορίστε κριτήρια για συνταξιδιώτη.',reset:'Επαναφορά',dest:'Προορισμός',dest_ph:'Αναζήτηση πόλης...',search_res:'Αποτελέσματα',pop_city:'Δημοφιλείς πόλεις',apply_as_is:' Αναζήτηση',date:'Ημερομηνία',sel_start:'Αναχώρηση',sel_end:'Επιστροφή',year:' ',month:' ',day:'',size:'Αριθμός ατόμων',all:'Δεν έχει σημασία',s_6_more:'6+',unit_p:' άτ.',apply:'Εφαρμογή ',unit_f:'',view_all:'Όλες οι ομάδες' },
    gdf: { activity:'Δραστηριότητα',tour:'Περιήγηση',food:'Εστιατόριο',cafe:'Καφέ',club:'Κλαμπ',any:'Όλα',gender:'Σύνθεση',g_2m2f:'2Α2Γ',g_3m1f:'3Α1Γ',g_1m3f:'1Α3Γ',g_all_m:'Μόνο άνδρες',g_all_f:'Μόνο γυναίκες',lang:'Γλώσσα',l_any:'Δεν έχει σημασία',l_any_desc:'Όλες οι γλώσσες',l_ko:'Κορεατικά',l_ko_desc:'Κυρίως κορεατικά',l_for:'Ξένα',l_for_desc:'Αγγλικά/ξένα',l_mix:'Μεικτά',l_mix_desc:'Πολυεθνικά',vibe:'Ατμόσφαιρα',v_any_desc:'Οποιαδήποτε',v_cas:'Χαλαρή',v_cas_desc:'Casual',v_party:'Πάρτι',v_party_desc:'Πάρτι!',v_ser:'Σοβαρή',v_ser_desc:'Στοχευμένη',title:'Φίλτρα ομάδας',desc:'Ορίστε κριτήρια.',reset:'Επαναφορά',chk:'Και check-in',cur:'Ομάδες σε ',based:'',apply:'Εφαρμογή ',unit:'',all:'Όλες οι ομάδες' }
  },
  uk: {
    gf: { c_tokyo:'Токіо',c_seoul:'Сеул',c_bangkok:'Бангкок',c_bali:'Балі',c_danang:'Дананг',c_sg:'Сінгапур',c_osaka:'Осака',c_taipei:'Тайбей',c_chiangmai:'Чіангмай',c_cebu:'Себу',c_bcn:'Барселона',c_paris:'Париж',n_jp:'Японія',n_kr:'Корея',n_th:'Таїланд',n_id:'Індонезія',n_vn:'В\'єтнам',n_sg:'Сінгапур',n_tw:'Тайвань',n_ph:'Філіппіни',n_es:'Іспанія',n_fr:'Франція',s_2:'2 ос.',s_3:'3 ос.',s_4:'4 ос.',s_5:'5 ос.',s_6:'6 ос.',w_sun:'Нд',w_mon:'Пн',w_tue:'Вт',w_wed:'Ср',w_thu:'Чт',w_fri:'Пт',w_sat:'Сб',m_1:'Січ',m_2:'Лют',m_3:'Бер',m_4:'Кві',m_5:'Тра',m_6:'Чер',m_7:'Лип',m_8:'Сер',m_9:'Вер',m_10:'Жов',m_11:'Лис',m_12:'Гру',p_we:'Цей вікенд',p_nw:'Наступного тижня',p_tm:'Цього місяця',p_nm:'Наступного місяця',title:'Фільтри подорожі',desc:'Встановіть критерії для супутника.',reset:'Скинути',dest:'Напрямок',dest_ph:'Пошук міста...',search_res:'Результати',pop_city:'Популярні міста',apply_as_is:' Пошук',date:'Дата',sel_start:'Відправлення',sel_end:'Повернення',year:' р.',month:' ',day:'',size:'Кількість осіб',all:'Не важливо',s_6_more:'6+',unit_p:' ос.',apply:'Застосувати ',unit_f:'',view_all:'Усі групи' },
    gdf: { activity:'Активність',tour:'Тур',food:'Ресторан',cafe:'Кафе',club:'Клуб',any:'Усе',gender:'Склад',g_2m2f:'2Ч2Ж',g_3m1f:'3Ч1Ж',g_1m3f:'1Ч3Ж',g_all_m:'Тільки чоловіки',g_all_f:'Тільки жінки',lang:'Мова',l_any:'Не важливо',l_any_desc:'Усі мови',l_ko:'Корейська',l_ko_desc:'Переважно корейська',l_for:'Іноземна',l_for_desc:'Англійська/іноземна',l_mix:'Змішана',l_mix_desc:'Міжнародна',vibe:'Атмосфера',v_any_desc:'Будь-яка',v_cas:'Розслаблена',v_cas_desc:'Casual',v_party:'Вечірка',v_party_desc:'Вечірка!',v_ser:'Серйозна',v_ser_desc:'Цілеспрямована',title:'Фільтри групи',desc:'Встановіть критерії.',reset:'Скинути',chk:'Також check-in',cur:'Групи в ',based:'',apply:'Застосувати ',unit:'',all:'Усі групи' }
  }
};

const entries = Object.entries(langs).map(([lang, val]) => `  ${lang}: ${JSON.stringify(val)}`).join(',\n');
c = c.slice(0, -2) + ',\n' + entries + '\n};\n';
fs.writeFileSync(fp, c, 'utf8');
console.log('Done. Languages added:', Object.keys(langs).join(', '));
console.log('Final size:', fs.statSync(fp).size, 'bytes');
