// add_checkin_langs.cjs - add remaining languages to checkinLocales.ts
const fs = require('fs');
const fp = 'src/i18n/checkinLocales.ts';
let c = fs.readFileSync(fp, 'utf8').trimEnd();
if (!c.endsWith('};')) { console.error('Unexpected ending'); process.exit(1); }

const langs = {
  fr: { checkin: { unknown_city:'Ville inconnue',unknown_country:'Pays inconnu',fetch_failed:'Impossible de récupérer les données de localisation.',perm_req:'La permission de localisation est requise.',error_occurred:'Une erreur s\'est produite lors du check-in.',title:'GPS Check-in d\'arrivée',desc1:'Enregistrez-vous dans votre ville actuelle et ',desc2:'des voyageurs dans la même ville',desc3:' vous seront proposés en priorité.',detect_btn:'Détecter ma position',locating:'Localisation en cours...',confirm_desc:'Confirmer le check-in à cet endroit ?',cancel:'Annuler',checkin_btn:'Check-in',done_badge:'Check-in effectué',people_here:'voyageurs dans cette ville',expires:'expiration automatique dans',checkout_btn:'Check-out' } },
  de: { checkin: { unknown_city:'Unbekannte Stadt',unknown_country:'Unbekanntes Land',fetch_failed:'Standortdaten konnten nicht abgerufen werden.',perm_req:'Standortberechtigung erforderlich.',error_occurred:'Beim Check-in ist ein Fehler aufgetreten.',title:'GPS Ankunfts-Check-in',desc1:'Checke in deiner aktuellen Stadt ein und ',desc2:'Reisende in derselben Stadt',desc3:' werden dir bevorzugt angezeigt.',detect_btn:'Meinen Standort erkennen',locating:'Standort wird ermittelt...',confirm_desc:'An diesem Ort einchecken?',cancel:'Abbrechen',checkin_btn:'Einchecken',done_badge:'Check-in abgeschlossen',people_here:'Reisende in dieser Stadt',expires:'automatisches Ablaufen in',checkout_btn:'Auschecken' } },
  pt: { checkin: { unknown_city:'Cidade desconhecida',unknown_country:'País desconhecido',fetch_failed:'Falha ao buscar dados de localização.',perm_req:'Permissão de localização necessária.',error_occurred:'Ocorreu um erro durante o check-in.',title:'Check-in GPS de chegada',desc1:'Faça check-in na sua cidade atual e ',desc2:'viajantes na mesma cidade',desc3:' serão priorizados nas sugestões.',detect_btn:'Detectar minha localização',locating:'Verificando localização...',confirm_desc:'Confirmar check-in neste local?',cancel:'Cancelar',checkin_btn:'Check-in',done_badge:'Check-in concluído',people_here:'viajantes nesta cidade',expires:'expira automaticamente em',checkout_btn:'Check-out' } },
  ru: { checkin: { unknown_city:'Неизвестный город',unknown_country:'Неизвестная страна',fetch_failed:'Не удалось получить данные о местоположении.',perm_req:'Требуется разрешение на геолокацию.',error_occurred:'При регистрации произошла ошибка.',title:'GPS-регистрация прибытия',desc1:'Зарегистрируйтесь в своём текущем городе и ',desc2:'путешественники в том же городе',desc3:' будут в приоритете.',detect_btn:'Определить моё местоположение',locating:'Определяем местоположение...',confirm_desc:'Зарегистрироваться здесь?',cancel:'Отмена',checkin_btn:'Регистрация',done_badge:'Регистрация завершена',people_here:'путешественников в этом городе',expires:'автоматическое истечение через',checkout_btn:'Выезд' } },
  ar: { checkin: { unknown_city:'مدينة غير معروفة',unknown_country:'دولة غير معروفة',fetch_failed:'فشل في جلب بيانات الموقع.',perm_req:'إذن الموقع مطلوب.',error_occurred:'حدث خطأ أثناء تسجيل الوصول.',title:'تسجيل الوصول GPS',desc1:'سجّل وصولك في مدينتك الحالية و',desc2:'المسافرون في نفس المدينة',desc3:' سيُعطَون الأولوية.',detect_btn:'اكتشاف موقعي',locating:'جارٍ التحقق من الموقع...',confirm_desc:'تأكيد تسجيل الوصول في هذا الموقع؟',cancel:'إلغاء',checkin_btn:'تسجيل الوصول',done_badge:'تم تسجيل الوصول',people_here:'مسافرون في هذه المدينة',expires:'انتهاء الصلاحية تلقائياً خلال',checkout_btn:'تسجيل المغادرة' } },
  hi: { checkin: { unknown_city:'अज्ञात शहर',unknown_country:'अज्ञात देश',fetch_failed:'स्थान डेटा प्राप्त करने में विफल।',perm_req:'स्थान अनुमति आवश्यक है।',error_occurred:'चेक-इन के दौरान एक त्रुटि हुई।',title:'GPS आगमन चेक-इन',desc1:'अपने वर्तमान शहर में चेक-इन करें और ',desc2:'उसी शहर के यात्री',desc3:' को प्राथमिकता दी जाएगी।',detect_btn:'मेरी स्थिति पता लगाएं',locating:'वर्तमान स्थान की जाँच की जा रही है...',confirm_desc:'इस स्थान पर चेक-इन करें?',cancel:'रद्द करें',checkin_btn:'चेक-इन',done_badge:'चेक-इन पूर्ण',people_here:'इस शहर में यात्री',expires:'स्वतः समाप्त',checkout_btn:'चेक-आउट' } },
  tr: { checkin: { unknown_city:'Bilinmeyen şehir',unknown_country:'Bilinmeyen ülke',fetch_failed:'Konum verileri alınamadı.',perm_req:'Konum izni gereklidir.',error_occurred:'Check-in sırasında bir hata oluştu.',title:'GPS Varış Check-in',desc1:'Bulunduğun şehre check-in yap ve ',desc2:'aynı şehirdeki gezginler',desc3:' önce önerilsin.',detect_btn:'Konumumu tespit et',locating:'Mevcut konum doğrulanıyor...',confirm_desc:'Bu konuma check-in yapılsın mı?',cancel:'İptal',checkin_btn:'Check-in',done_badge:'Check-in tamamlandı',people_here:'bu şehirde gezgin',expires:'sonra otomatik sona erer',checkout_btn:'Check-out' } },
  it: { checkin: { unknown_city:'Città sconosciuta',unknown_country:'Paese sconosciuto',fetch_failed:'Impossibile recuperare i dati di posizione.',perm_req:'Permesso posizione richiesto.',error_occurred:'Si è verificato un errore durante il check-in.',title:'Check-in GPS arrivo',desc1:'Fai il check-in nella tua città attuale e ',desc2:'i viaggiatori nella stessa città',desc3:' saranno mostrati prima.',detect_btn:'Rileva la mia posizione',locating:'Verifica posizione in corso...',confirm_desc:'Confermare il check-in in questa posizione?',cancel:'Annulla',checkin_btn:'Check-in',done_badge:'Check-in completato',people_here:'viaggiatori in questa città',expires:'scadenza automatica tra',checkout_btn:'Check-out' } },
  nl: { checkin: { unknown_city:'Onbekende stad',unknown_country:'Onbekend land',fetch_failed:'Locatiegegevens ophalen mislukt.',perm_req:'Locatietoestemming vereist.',error_occurred:'Er is een fout opgetreden tijdens de check-in.',title:'GPS aankomst check-in',desc1:'Meld je aan in je huidige stad en ',desc2:'reizigers in dezelfde stad',desc3:' worden prioriteit gegeven.',detect_btn:'Detecteer mijn locatie',locating:'Locatie controleren...',confirm_desc:'Inchecken op deze locatie?',cancel:'Annuleren',checkin_btn:'Inchecken',done_badge:'Check-in voltooid',people_here:'reizigers in deze stad',expires:'automatisch verlopen over',checkout_btn:'Uitchecken' } },
  pl: { checkin: { unknown_city:'Nieznane miasto',unknown_country:'Nieznany kraj',fetch_failed:'Nie udało się pobrać danych lokalizacji.',perm_req:'Wymagana jest zgoda na lokalizację.',error_occurred:'Podczas zameldowania wystąpił błąd.',title:'GPS Zameldowanie po przyjeździe',desc1:'Zamelduj się w swoim aktualnym mieście i ',desc2:'podróżnicy w tym samym mieście',desc3:' będą priorytetowi.',detect_btn:'Wykryj moją lokalizację',locating:'Sprawdzanie aktualnej lokalizacji...',confirm_desc:'Zameldować się w tej lokalizacji?',cancel:'Anuluj',checkin_btn:'Zameldowanie',done_badge:'Zameldowanie zakończone',people_here:'podróżnych w tym mieście',expires:'automatyczne wygaśnięcie za',checkout_btn:'Wymeldowanie' } },
  sv: { checkin: { unknown_city:'Okänd stad',unknown_country:'Okänt land',fetch_failed:'Det gick inte att hämta platsdata.',perm_req:'Platstillstånd krävs.',error_occurred:'Ett fel uppstod under incheckning.',title:'GPS ankomst-incheckning',desc1:'Checka in i din nuvarande stad och ',desc2:'resenärer i samma stad',desc3:' prioriteras.',detect_btn:'Identifiera min plats',locating:'Kontrollerar aktuell plats...',confirm_desc:'Checka in på den här platsen?',cancel:'Avbryt',checkin_btn:'Checka in',done_badge:'Incheckning klar',people_here:'resenärer i den här staden',expires:'automatisk utgång om',checkout_btn:'Checka ut' } },
  da: { checkin: { unknown_city:'Ukendt by',unknown_country:'Ukendt land',fetch_failed:'Pladsdata kunne ikke hentes.',perm_req:'Placeringstilladelse påkrævet.',error_occurred:'Der opstod en fejl under check-in.',title:'GPS ankomst check-in',desc1:'Tjek ind i din aktuelle by og ',desc2:'rejsende i samme by',desc3:' prioriteres.',detect_btn:'Find min placering',locating:'Kontrollerer aktuel placering...',confirm_desc:'Check ind på dette sted?',cancel:'Annuller',checkin_btn:'Check in',done_badge:'Check-in fuldført',people_here:'rejsende i denne by',expires:'automatisk udløb om',checkout_btn:'Check ud' } },
  no: { checkin: { unknown_city:'Ukjent by',unknown_country:'Ukjent land',fetch_failed:'Kunne ikke hente stedsdata.',perm_req:'Posisjonstillatelse kreves.',error_occurred:'Det oppstod en feil under innsjekking.',title:'GPS ankomst-innsjekk',desc1:'Sjekk inn i din nåværende by og ',desc2:'reisende i samme by',desc3:' prioriteres.',detect_btn:'Finn min posisjon',locating:'Kontrollerer gjeldende posisjon...',confirm_desc:'Sjekke inn på dette stedet?',cancel:'Avbryt',checkin_btn:'Sjekk inn',done_badge:'Innsjekk fullført',people_here:'reisende i denne byen',expires:'automatisk utløp om',checkout_btn:'Sjekk ut' } },
  fi: { checkin: { unknown_city:'Tuntematon kaupunki',unknown_country:'Tuntematon maa',fetch_failed:'Sijaintitietojen hakeminen epäonnistui.',perm_req:'Sijaintilupa vaaditaan.',error_occurred:'Kirjautumisessa tapahtui virhe.',title:'GPS saapumiskirjautuminen',desc1:'Kirjaudu nykyiseen kaupunkiisi ja ',desc2:'samassa kaupungissa olevat matkustajat',desc3:' priorisoidaan.',detect_btn:'Tunnista sijaintini',locating:'Tarkistetaan nykyistä sijaintia...',confirm_desc:'Kirjaudu tähän sijaintiin?',cancel:'Peruuta',checkin_btn:'Kirjaudu',done_badge:'Kirjautuminen valmis',people_here:'matkustajaa tässä kaupungissa',expires:'automaattinen vanheneminen',checkout_btn:'Kirjaudu ulos' } },
  cs: { checkin: { unknown_city:'Neznámé město',unknown_country:'Neznámá země',fetch_failed:'Načtení dat o poloze se nezdařilo.',perm_req:'Je vyžadováno oprávnění k poloze.',error_occurred:'Při přihlášení nastala chyba.',title:'GPS příjezdové přihlášení',desc1:'Přihlaste se ve svém aktuálním městě a ',desc2:'cestovatelé ve stejném městě',desc3:' budou upřednostněni.',detect_btn:'Zjistit moji polohu',locating:'Ověřování aktuální polohy...',confirm_desc:'Přihlásit se na tomto místě?',cancel:'Zrušit',checkin_btn:'Přihlásit se',done_badge:'Přihlášení dokončeno',people_here:'cestovatelů v tomto městě',expires:'automatické vypršení za',checkout_btn:'Odhlásit se' } },
  ro: { checkin: { unknown_city:'Oraș necunoscut',unknown_country:'Țară necunoscută',fetch_failed:'Preluarea datelor de locație a eșuat.',perm_req:'Permisiunea de locație este necesară.',error_occurred:'A apărut o eroare la check-in.',title:'GPS check-in la sosire',desc1:'Faceți check-in în orașul dvs. actual și ',desc2:'călătorii din același oraș',desc3:' vor fi prioritizați.',detect_btn:'Detectați locația mea',locating:'Se verifică locația curentă...',confirm_desc:'Confirmare check-in la această locație?',cancel:'Anulare',checkin_btn:'Check-in',done_badge:'Check-in finalizat',people_here:'călători în acest oraș',expires:'expirare automată în',checkout_btn:'Check-out' } },
  hu: { checkin: { unknown_city:'Ismeretlen város',unknown_country:'Ismeretlen ország',fetch_failed:'A helyadatok lekérése sikertelen.',perm_req:'Helymeghatározási engedély szükséges.',error_occurred:'Hiba történt a bejelentkezés során.',title:'GPS érkezési bejelentkezés',desc1:'Jelentkezz be a jelenlegi városodba és ',desc2:'ugyanabban a városban lévő utazók',desc3:' prioritást kapnak.',detect_btn:'Helyzetmeghatározás',locating:'Jelenlegi helyzet ellenőrzése...',confirm_desc:'Bejelentkezés erre a helyre?',cancel:'Mégse',checkin_btn:'Bejelentkezés',done_badge:'Bejelentkezés kész',people_here:'utazó ebben a városban',expires:'automatikus lejárat',checkout_btn:'Kijelentkezés' } },
  el: { checkin: { unknown_city:'Άγνωστη πόλη',unknown_country:'Άγνωστη χώρα',fetch_failed:'Αποτυχία ανάκτησης δεδομένων τοποθεσίας.',perm_req:'Απαιτείται άδεια τοποθεσίας.',error_occurred:'Παρουσιάστηκε σφάλμα κατά το check-in.',title:'GPS Αφιξη check-in',desc1:'Κάντε check-in στην τρέχουσα πόλη σας και ',desc2:'οι ταξιδιώτες στην ίδια πόλη',desc3:' θα επιλεγούν κατά προτεραιότητα.',detect_btn:'Εντοπισμός τοποθεσίας μου',locating:'Επαλήθευση τρέχουσας τοποθεσίας...',confirm_desc:'Επιβεβαίωση check-in σε αυτή την τοποθεσία;',cancel:'Ακύρωση',checkin_btn:'Check-in',done_badge:'Check-in ολοκληρώθηκε',people_here:'ταξιδιώτες σε αυτή την πόλη',expires:'αυτόματη λήξη σε',checkout_btn:'Check-out' } },
  uk: { checkin: { unknown_city:'Невідоме місто',unknown_country:'Невідома країна',fetch_failed:'Не вдалося отримати дані місцезнаходження.',perm_req:'Потрібен дозвіл на геолокацію.',error_occurred:'Під час реєстрації сталася помилка.',title:'GPS реєстрація прибуття',desc1:'Зареєструйтесь у своєму поточному місті і ',desc2:'мандрівники в тому ж місті',desc3:' отримають пріоритет.',detect_btn:'Визначити моє місцезнаходження',locating:'Перевіряємо поточне місцезнаходження...',confirm_desc:'Зареєструватись у цьому місці?',cancel:'Скасувати',checkin_btn:'Реєстрація',done_badge:'Реєстрацію завершено',people_here:'мандрівників у цьому місті',expires:'автоматичне закінчення через',checkout_btn:'Виїзд' } }
};

const entries = Object.entries(langs).map(([lang, val]) => `  ${lang}: ${JSON.stringify(val)}`).join(',\n');
c = c.slice(0, -2) + ',\n' + entries + '\n};\n';
fs.writeFileSync(fp, c, 'utf8');
console.log('Done. Languages added:', Object.keys(langs).join(', '));
console.log('Final size:', fs.statSync(fp).size, 'bytes');
