// add_filter_langs2.cjs - remaining languages
const fs = require('fs');
const fp = 'src/i18n/filterLocales.ts';
let c = fs.readFileSync(fp, 'utf8').trimEnd();
if (!c.endsWith('};')) { console.error('Unexpected ending'); process.exit(1); }

const langs = {
  es: {
    gf: { c_tokyo:'Tokio',c_seoul:'Seúl',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapur',c_osaka:'Osaka',c_taipei:'Taipéi',c_chiangmai:'Chiang Mai',c_cebu:'Cebú',c_bcn:'Barcelona',c_paris:'París',n_jp:'Japón',n_kr:'Corea',n_th:'Tailandia',n_id:'Indonesia',n_vn:'Vietnam',n_sg:'Singapur',n_tw:'Taiwán',n_ph:'Filipinas',n_es:'España',n_fr:'Francia',s_2:'2 pers.',s_3:'3 pers.',s_4:'4 pers.',s_5:'5 pers.',s_6:'6 pers.',w_sun:'Dom',w_mon:'Lun',w_tue:'Mar',w_wed:'Mié',w_thu:'Jue',w_fri:'Vie',w_sat:'Sáb',m_1:'Ene',m_2:'Feb',m_3:'Mar',m_4:'Abr',m_5:'May',m_6:'Jun',m_7:'Jul',m_8:'Ago',m_9:'Sep',m_10:'Oct',m_11:'Nov',m_12:'Dic',p_we:'Este fin de semana',p_nw:'Próxima semana',p_tm:'Este mes',p_nm:'Próximo mes',title:'Filtros de viaje',desc:'Define los criterios de tu compañero.',reset:'Restablecer',dest:'Destino',dest_ph:'Buscar ciudad...',search_res:'Resultados',pop_city:'Ciudades populares',apply_as_is:' Buscar',date:'Fecha',sel_start:'Salida',sel_end:'Regreso',year:' ',month:' ',day:'',size:'Nº de personas',all:'No importa',s_6_more:'6+',unit_p:'',apply:'Aplicar ',unit_f:'',view_all:'Ver todos los grupos' },
    gdf: { activity:'Actividad',tour:'Tour',food:'Restaurante',cafe:'Café',club:'Club',any:'Todos',gender:'Composición',g_2m2f:'2H2M',g_3m1f:'3H1M',g_1m3f:'1H3M',g_all_m:'Solo hombres',g_all_f:'Solo mujeres',lang:'Idioma',l_any:'No importa',l_any_desc:'Todos los idiomas',l_ko:'Coreano',l_ko_desc:'Principalmente coreano',l_for:'Extranjero',l_for_desc:'Inglés/extranjero',l_mix:'Mixto',l_mix_desc:'Multinacional',vibe:'Ambiente',v_any_desc:'Cualquier ambiente',v_cas:'Relajado',v_cas_desc:'Casual',v_party:'Fiesta',v_party_desc:'¡Fiesta!',v_ser:'Serio',v_ser_desc:'Viaje con propósito',title:'Filtros de grupo',desc:'Define los criterios.',reset:'Restablecer',chk:'Check-in también',cur:'Grupos en ',based:'',apply:'Aplicar ',unit:'',all:'Ver todos los grupos' }
  },
  id: {
    gf: { c_tokyo:'Tokyo',c_seoul:'Seoul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapura',c_osaka:'Osaka',c_taipei:'Taipei',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Paris',n_jp:'Jepang',n_kr:'Korea',n_th:'Thailand',n_id:'Indonesia',n_vn:'Vietnam',n_sg:'Singapura',n_tw:'Taiwan',n_ph:'Filipina',n_es:'Spanyol',n_fr:'Prancis',s_2:'2 org.',s_3:'3 org.',s_4:'4 org.',s_5:'5 org.',s_6:'6 org.',w_sun:'Min',w_mon:'Sen',w_tue:'Sel',w_wed:'Rab',w_thu:'Kam',w_fri:'Jum',w_sat:'Sab',m_1:'Jan',m_2:'Feb',m_3:'Mar',m_4:'Apr',m_5:'Mei',m_6:'Jun',m_7:'Jul',m_8:'Agu',m_9:'Sep',m_10:'Okt',m_11:'Nov',m_12:'Des',p_we:'Akhir pekan ini',p_nw:'Minggu depan',p_tm:'Bulan ini',p_nm:'Bulan depan',title:'Filter perjalanan',desc:'Tetapkan kriteria teman perjalanan.',reset:'Reset',dest:'Tujuan',dest_ph:'Cari kota...',search_res:'Hasil',pop_city:'Kota populer',apply_as_is:' Cari',date:'Tanggal',sel_start:'Keberangkatan',sel_end:'Kepulangan',year:' ',month:' ',day:'',size:'Jumlah orang',all:'Tidak masalah',s_6_more:'6+',unit_p:' org.',apply:'Terapkan ',unit_f:'',view_all:'Semua grup' },
    gdf: { activity:'Aktivitas',tour:'Tur',food:'Restoran',cafe:'Kafe',club:'Klub',any:'Semua',gender:'Komposisi',g_2m2f:'2P2W',g_3m1f:'3P1W',g_1m3f:'1P3W',g_all_m:'Pria saja',g_all_f:'Wanita saja',lang:'Bahasa',l_any:'Tidak masalah',l_any_desc:'Semua bahasa',l_ko:'Korea',l_ko_desc:'Utamanya Korea',l_for:'Asing',l_for_desc:'Inggris/asing',l_mix:'Campuran',l_mix_desc:'Multinasional',vibe:'Suasana',v_any_desc:'Suasana apa saja',v_cas:'Santai',v_cas_desc:'Casual',v_party:'Pesta',v_party_desc:'Bersenang-senang!',v_ser:'Serius',v_ser_desc:'Bertujuan',title:'Filter grup',desc:'Tetapkan kriteria teman.',reset:'Reset',chk:'Check-in juga',cur:'Grup di ',based:'',apply:'Terapkan ',unit:'',all:'Semua grup' }
  },
  vi: {
    gf: { c_tokyo:'Tokyo',c_seoul:'Seoul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Đà Nẵng',c_sg:'Singapore',c_osaka:'Osaka',c_taipei:'Đài Bắc',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Paris',n_jp:'Nhật Bản',n_kr:'Hàn Quốc',n_th:'Thái Lan',n_id:'Indonesia',n_vn:'Việt Nam',n_sg:'Singapore',n_tw:'Đài Loan',n_ph:'Philippines',n_es:'Tây Ban Nha',n_fr:'Pháp',s_2:'2 người',s_3:'3 người',s_4:'4 người',s_5:'5 người',s_6:'6 người',w_sun:'CN',w_mon:'T2',w_tue:'T3',w_wed:'T4',w_thu:'T5',w_fri:'T6',w_sat:'T7',m_1:'Th.1',m_2:'Th.2',m_3:'Th.3',m_4:'Th.4',m_5:'Th.5',m_6:'Th.6',m_7:'Th.7',m_8:'Th.8',m_9:'Th.9',m_10:'Th.10',m_11:'Th.11',m_12:'Th.12',p_we:'Cuối tuần này',p_nw:'Tuần sau',p_tm:'Tháng này',p_nm:'Tháng sau',title:'Bộ lọc du lịch',desc:'Đặt tiêu chí bạn đồng hành.',reset:'Đặt lại',dest:'Điểm đến',dest_ph:'Tìm thành phố...',search_res:'Kết quả',pop_city:'Thành phố phổ biến',apply_as_is:' Tìm kiếm',date:'Ngày',sel_start:'Ngày đi',sel_end:'Ngày về',year:' ',month:' ',day:'',size:'Số người',all:'Không quan trọng',s_6_more:'6+',unit_p:' người',apply:'Áp dụng ',unit_f:'',view_all:'Tất cả nhóm' },
    gdf: { activity:'Hoạt động',tour:'Tour',food:'Nhà hàng',cafe:'Cà phê',club:'Club',any:'Tất cả',gender:'Thành phần',g_2m2f:'2Nam2Nữ',g_3m1f:'3Nam1Nữ',g_1m3f:'1Nam3Nữ',g_all_m:'Chỉ nam',g_all_f:'Chỉ nữ',lang:'Ngôn ngữ',l_any:'Không quan trọng',l_any_desc:'Tất cả ngôn ngữ',l_ko:'Tiếng Hàn',l_ko_desc:'Chủ yếu tiếng Hàn',l_for:'Nước ngoài',l_for_desc:'Tiếng Anh/ngoại ngữ',l_mix:'Hỗn hợp',l_mix_desc:'Đa quốc gia',vibe:'Không khí',v_any_desc:'Bất kỳ',v_cas:'Thoải mái',v_cas_desc:'Casual',v_party:'Tiệc',v_party_desc:'Vui vẻ!',v_ser:'Nghiêm túc',v_ser_desc:'Có mục đích',title:'Bộ lọc nhóm',desc:'Đặt tiêu chí bạn đồng hành.',reset:'Đặt lại',chk:'Check-in cũng được',cur:'Nhóm tại ',based:'',apply:'Áp dụng ',unit:'',all:'Tất cả nhóm' }
  },
  zh: {
    gf: { c_tokyo:'东京',c_seoul:'首尔',c_bangkok:'曼谷',c_bali:'巴厘岛',c_danang:'岘港',c_sg:'新加坡',c_osaka:'大阪',c_taipei:'台北',c_chiangmai:'清迈',c_cebu:'宿务',c_bcn:'巴塞罗那',c_paris:'巴黎',n_jp:'日本',n_kr:'韩国',n_th:'泰国',n_id:'印度尼西亚',n_vn:'越南',n_sg:'新加坡',n_tw:'台湾',n_ph:'菲律宾',n_es:'西班牙',n_fr:'法国',s_2:'2人',s_3:'3人',s_4:'4人',s_5:'5人',s_6:'6人',w_sun:'日',w_mon:'一',w_tue:'二',w_wed:'三',w_thu:'四',w_fri:'五',w_sat:'六',m_1:'1月',m_2:'2月',m_3:'3月',m_4:'4月',m_5:'5月',m_6:'6月',m_7:'7月',m_8:'8月',m_9:'9月',m_10:'10月',m_11:'11月',m_12:'12月',p_we:'本周末',p_nw:'下周',p_tm:'本月',p_nm:'下月',title:'旅行筛选',desc:'设置旅伴条件。',reset:'重置',dest:'目的地',dest_ph:'搜索城市...',search_res:'搜索结果',pop_city:'热门城市',apply_as_is:' 搜索',date:'日期',sel_start:'出发日期',sel_end:'返回日期',year:'年',month:'月',day:'日',size:'人数',all:'不限',s_6_more:'6人以上',unit_p:'人',apply:'应用 ',unit_f:'个',view_all:'查看全部群组' },
    gdf: { activity:'活动类型',tour:'旅游',food:'美食',cafe:'咖啡馆',club:'俱乐部',any:'全部',gender:'性别组合',g_2m2f:'2男2女',g_3m1f:'3男1女',g_1m3f:'1男3女',g_all_m:'仅限男性',g_all_f:'仅限女性',lang:'语言',l_any:'不限',l_any_desc:'所有语言',l_ko:'韩语',l_ko_desc:'以韩语为主',l_for:'外国人',l_for_desc:'英语/外语',l_mix:'混合',l_mix_desc:'多国籍',vibe:'氛围',v_any_desc:'不限氛围',v_cas:'休闲',v_cas_desc:'轻松随意',v_party:'派对',v_party_desc:'尽情享乐！',v_ser:'认真',v_ser_desc:'目的明确的旅行',title:'群组筛选',desc:'设置旅伴条件。',reset:'重置',chk:'同时签到',cur:'当前位置',based:'附近',apply:'应用 ',unit:'个',all:'查看全部群组' }
  },
  nl: {
    gf: { c_tokyo:'Tokio',c_seoul:'Seoul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapore',c_osaka:'Osaka',c_taipei:'Taipei',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Parijs',n_jp:'Japan',n_kr:'Korea',n_th:'Thailand',n_id:'Indonesië',n_vn:'Vietnam',n_sg:'Singapore',n_tw:'Taiwan',n_ph:'Filipijnen',n_es:'Spanje',n_fr:'Frankrijk',s_2:'2 pers.',s_3:'3 pers.',s_4:'4 pers.',s_5:'5 pers.',s_6:'6 pers.',w_sun:'zo',w_mon:'ma',w_tue:'di',w_wed:'wo',w_thu:'do',w_fri:'vr',w_sat:'za',m_1:'jan',m_2:'feb',m_3:'mrt',m_4:'apr',m_5:'mei',m_6:'jun',m_7:'jul',m_8:'aug',m_9:'sep',m_10:'okt',m_11:'nov',m_12:'dec',p_we:'Dit weekend',p_nw:'Volgende week',p_tm:'Deze maand',p_nm:'Volgende maand',title:'Reisfilters',desc:'Stel criteria voor reisgenoot in.',reset:'Resetten',dest:'Bestemming',dest_ph:'Stad zoeken...',search_res:'Resultaten',pop_city:'Populaire steden',apply_as_is:' Zoeken',date:'Datum',sel_start:'Vertrekdatum',sel_end:'Retourdatum',year:' ',month:' ',day:'',size:'Aantal personen',all:'Geen voorkeur',s_6_more:'6+',unit_p:'',apply:'Toepassen ',unit_f:'',view_all:'Alle groepen bekijken' },
    gdf: { activity:'Activiteit',tour:'Tour',food:'Restaurant',cafe:'Café',club:'Club',any:'Alle',gender:'Samenstelling',g_2m2f:'2M2V',g_3m1f:'3M1V',g_1m3f:'1M3V',g_all_m:'Alleen mannen',g_all_f:'Alleen vrouwen',lang:'Taal',l_any:'Geen voorkeur',l_any_desc:'Alle talen',l_ko:'Koreaans',l_ko_desc:'Voornamelijk Koreaans',l_for:'Buitenlands',l_for_desc:'Engels/buitenlands',l_mix:'Gemengd',l_mix_desc:'Multinationaal',vibe:'Sfeer',v_any_desc:'Alle sferen',v_cas:'Ontspannen',v_cas_desc:'Casual',v_party:'Feest',v_party_desc:'Feest!',v_ser:'Serieus',v_ser_desc:'Doelgericht',title:'Groepsfilters',desc:'Stel criteria in.',reset:'Resetten',chk:'Ook inchecken',cur:'Groepen in ',based:'',apply:'Toepassen ',unit:'',all:'Alle groepen' }
  },
  pl: {
    gf: { c_tokyo:'Tokio',c_seoul:'Seul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapur',c_osaka:'Osaka',c_taipei:'Tajpej',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Paryż',n_jp:'Japonia',n_kr:'Korea',n_th:'Tajlandia',n_id:'Indonezja',n_vn:'Wietnam',n_sg:'Singapur',n_tw:'Tajwan',n_ph:'Filipiny',n_es:'Hiszpania',n_fr:'Francja',s_2:'2 os.',s_3:'3 os.',s_4:'4 os.',s_5:'5 os.',s_6:'6 os.',w_sun:'Nd',w_mon:'Pn',w_tue:'Wt',w_wed:'Śr',w_thu:'Cz',w_fri:'Pt',w_sat:'So',m_1:'Sty',m_2:'Lut',m_3:'Mar',m_4:'Kwi',m_5:'Maj',m_6:'Cze',m_7:'Lip',m_8:'Sie',m_9:'Wrz',m_10:'Paź',m_11:'Lis',m_12:'Gru',p_we:'Ten weekend',p_nw:'Przyszły tydzień',p_tm:'Ten miesiąc',p_nm:'Przyszły miesiąc',title:'Filtry podróży',desc:'Ustaw kryteria towarzysza.',reset:'Resetuj',dest:'Cel podróży',dest_ph:'Szukaj miasta...',search_res:'Wyniki',pop_city:'Popularne miasta',apply_as_is:' Szukaj',date:'Data',sel_start:'Wyjazd',sel_end:'Powrót',year:' ',month:' ',day:'',size:'Liczba osób',all:'Nieważne',s_6_more:'6+',unit_p:' os.',apply:'Zastosuj ',unit_f:'',view_all:'Wszystkie grupy' },
    gdf: { activity:'Aktywność',tour:'Wycieczka',food:'Restauracja',cafe:'Kawiarnia',club:'Klub',any:'Wszystkie',gender:'Skład',g_2m2f:'2M2K',g_3m1f:'3M1K',g_1m3f:'1M3K',g_all_m:'Tylko mężczyźni',g_all_f:'Tylko kobiety',lang:'Język',l_any:'Nieważne',l_any_desc:'Wszystkie języki',l_ko:'Koreański',l_ko_desc:'Głównie koreański',l_for:'Zagraniczny',l_for_desc:'Angielski/zagraniczny',l_mix:'Mieszany',l_mix_desc:'Wielonarodowy',vibe:'Atmosfera',v_any_desc:'Dowolna',v_cas:'Relaks',v_cas_desc:'Casual',v_party:'Impreza',v_party_desc:'Impreza!',v_ser:'Poważna',v_ser_desc:'Z celem',title:'Filtry grupy',desc:'Ustaw kryteria.',reset:'Resetuj',chk:'Też zamelduj',cur:'Grupy w ',based:'',apply:'Zastosuj ',unit:'',all:'Wszystkie grupy' }
  },
  sv: {
    gf: { c_tokyo:'Tokyo',c_seoul:'Seoul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapore',c_osaka:'Osaka',c_taipei:'Taipei',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Paris',n_jp:'Japan',n_kr:'Korea',n_th:'Thailand',n_id:'Indonesien',n_vn:'Vietnam',n_sg:'Singapore',n_tw:'Taiwan',n_ph:'Filippinerna',n_es:'Spanien',n_fr:'Frankrike',s_2:'2 pers.',s_3:'3 pers.',s_4:'4 pers.',s_5:'5 pers.',s_6:'6 pers.',w_sun:'Sön',w_mon:'Mån',w_tue:'Tis',w_wed:'Ons',w_thu:'Tor',w_fri:'Fre',w_sat:'Lör',m_1:'Jan',m_2:'Feb',m_3:'Mar',m_4:'Apr',m_5:'Maj',m_6:'Jun',m_7:'Jul',m_8:'Aug',m_9:'Sep',m_10:'Okt',m_11:'Nov',m_12:'Dec',p_we:'Den här helgen',p_nw:'Nästa vecka',p_tm:'Den här månaden',p_nm:'Nästa månad',title:'Resefilter',desc:'Ange kriterier för resekompis.',reset:'Återställ',dest:'Destination',dest_ph:'Sök stad...',search_res:'Resultat',pop_city:'Populära städer',apply_as_is:' Sök',date:'Datum',sel_start:'Avresa',sel_end:'Hemkomst',year:' ',month:' ',day:'',size:'Antal personer',all:'Spelar ingen roll',s_6_more:'6+',unit_p:'',apply:'Verkställ ',unit_f:'',view_all:'Visa alla grupper' },
    gdf: { activity:'Aktivitet',tour:'Tur',food:'Restaurang',cafe:'Café',club:'Klubb',any:'Alla',gender:'Sammansättning',g_2m2f:'2M2K',g_3m1f:'3M1K',g_1m3f:'1M3K',g_all_m:'Bara män',g_all_f:'Bara kvinnor',lang:'Språk',l_any:'Spelar ingen roll',l_any_desc:'Alla språk',l_ko:'Koreanska',l_ko_desc:'Huvudsakligen koreanska',l_for:'Utländskt',l_for_desc:'Engelska/utländskt',l_mix:'Blandat',l_mix_desc:'Multinationellt',vibe:'Stämning',v_any_desc:'Alla stämningar',v_cas:'Avslappnad',v_cas_desc:'Casual',v_party:'Fest',v_party_desc:'Fest!',v_ser:'Seriös',v_ser_desc:'Målinriktad',title:'Gruppfilter',desc:'Ange kriterier.',reset:'Återställ',chk:'Checka in också',cur:'Grupper i ',based:'',apply:'Verkställ ',unit:'',all:'Alla grupper' }
  },
  da: {
    gf: { c_tokyo:'Tokyo',c_seoul:'Seoul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapore',c_osaka:'Osaka',c_taipei:'Taipei',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Paris',n_jp:'Japan',n_kr:'Korea',n_th:'Thailand',n_id:'Indonesien',n_vn:'Vietnam',n_sg:'Singapore',n_tw:'Taiwan',n_ph:'Filippinerne',n_es:'Spanien',n_fr:'Frankrig',s_2:'2 pers.',s_3:'3 pers.',s_4:'4 pers.',s_5:'5 pers.',s_6:'6 pers.',w_sun:'Søn',w_mon:'Man',w_tue:'Tir',w_wed:'Ons',w_thu:'Tor',w_fri:'Fre',w_sat:'Lør',m_1:'Jan',m_2:'Feb',m_3:'Mar',m_4:'Apr',m_5:'Maj',m_6:'Jun',m_7:'Jul',m_8:'Aug',m_9:'Sep',m_10:'Okt',m_11:'Nov',m_12:'Dec',p_we:'Denne weekend',p_nw:'Næste uge',p_tm:'Denne måned',p_nm:'Næste måned',title:'Rejsefiltre',desc:'Angiv kriterier for rejsekammerat.',reset:'Nulstil',dest:'Destination',dest_ph:'Søg by...',search_res:'Resultater',pop_city:'Populære byer',apply_as_is:' Søg',date:'Dato',sel_start:'Afrejse',sel_end:'Hjemkomst',year:' ',month:' ',day:'',size:'Antal personer',all:'Ligegyldigt',s_6_more:'6+',unit_p:'',apply:'Anvend ',unit_f:'',view_all:'Se alle grupper' },
    gdf: { activity:'Aktivitet',tour:'Tur',food:'Restaurant',cafe:'Café',club:'Klub',any:'Alle',gender:'Sammensætning',g_2m2f:'2M2K',g_3m1f:'3M1K',g_1m3f:'1M3K',g_all_m:'Kun mænd',g_all_f:'Kun kvinder',lang:'Sprog',l_any:'Ligegyldigt',l_any_desc:'Alle sprog',l_ko:'Koreansk',l_ko_desc:'Primært koreansk',l_for:'Udenlandsk',l_for_desc:'Engelsk/udenlandsk',l_mix:'Blandet',l_mix_desc:'Multinationalt',vibe:'Stemning',v_any_desc:'Alle stemninger',v_cas:'Afslappet',v_cas_desc:'Casual',v_party:'Fest',v_party_desc:'Fest!',v_ser:'Seriøs',v_ser_desc:'Målrettet',title:'Gruppefiltre',desc:'Angiv kriterier.',reset:'Nulstil',chk:'Tjek ind også',cur:'Grupper i ',based:'',apply:'Anvend ',unit:'',all:'Alle grupper' }
  },
  no: {
    gf: { c_tokyo:'Tokyo',c_seoul:'Seoul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapore',c_osaka:'Osaka',c_taipei:'Taipei',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Paris',n_jp:'Japan',n_kr:'Korea',n_th:'Thailand',n_id:'Indonesia',n_vn:'Vietnam',n_sg:'Singapore',n_tw:'Taiwan',n_ph:'Filippinene',n_es:'Spania',n_fr:'Frankrike',s_2:'2 pers.',s_3:'3 pers.',s_4:'4 pers.',s_5:'5 pers.',s_6:'6 pers.',w_sun:'Søn',w_mon:'Man',w_tue:'Tir',w_wed:'Ons',w_thu:'Tor',w_fri:'Fre',w_sat:'Lør',m_1:'Jan',m_2:'Feb',m_3:'Mar',m_4:'Apr',m_5:'Mai',m_6:'Jun',m_7:'Jul',m_8:'Aug',m_9:'Sep',m_10:'Okt',m_11:'Nov',m_12:'Des',p_we:'Denne helgen',p_nw:'Neste uke',p_tm:'Denne måneden',p_nm:'Neste måned',title:'Reisefiltre',desc:'Angi kriterier for reisepartner.',reset:'Tilbakestill',dest:'Destinasjon',dest_ph:'Søk by...',search_res:'Resultater',pop_city:'Populære byer',apply_as_is:' Søk',date:'Dato',sel_start:'Avreise',sel_end:'Hjemkomst',year:' ',month:' ',day:'',size:'Antall personer',all:'Spiller ingen rolle',s_6_more:'6+',unit_p:'',apply:'Bruk ',unit_f:'',view_all:'Se alle grupper' },
    gdf: { activity:'Aktivitet',tour:'Tur',food:'Restaurant',cafe:'Kafé',club:'Klubb',any:'Alle',gender:'Sammensetning',g_2m2f:'2M2K',g_3m1f:'3M1K',g_1m3f:'1M3K',g_all_m:'Kun menn',g_all_f:'Kun kvinner',lang:'Språk',l_any:'Spiller ingen rolle',l_any_desc:'Alle språk',l_ko:'Koreansk',l_ko_desc:'Primært koreansk',l_for:'Utenlandsk',l_for_desc:'Engelsk/utenlandsk',l_mix:'Blandet',l_mix_desc:'Multinasjonalt',vibe:'Stemning',v_any_desc:'Alle stemninger',v_cas:'Avslappet',v_cas_desc:'Casual',v_party:'Fest',v_party_desc:'Fest!',v_ser:'Seriøs',v_ser_desc:'Målrettet',title:'Gruppefiltre',desc:'Angi kriterier.',reset:'Tilbakestill',chk:'Sjekk inn også',cur:'Grupper i ',based:'',apply:'Bruk ',unit:'',all:'Alle grupper' }
  },
  fi: {
    gf: { c_tokyo:'Tokio',c_seoul:'Soul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapore',c_osaka:'Osaka',c_taipei:'Taipei',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Pariisi',n_jp:'Japani',n_kr:'Korea',n_th:'Thaimaa',n_id:'Indonesia',n_vn:'Vietnam',n_sg:'Singapore',n_tw:'Taiwan',n_ph:'Filippiinit',n_es:'Espanja',n_fr:'Ranska',s_2:'2 hlö.',s_3:'3 hlö.',s_4:'4 hlö.',s_5:'5 hlö.',s_6:'6 hlö.',w_sun:'Su',w_mon:'Ma',w_tue:'Ti',w_wed:'Ke',w_thu:'To',w_fri:'Pe',w_sat:'La',m_1:'Tam',m_2:'Hel',m_3:'Maa',m_4:'Huh',m_5:'Tou',m_6:'Kes',m_7:'Hei',m_8:'Elo',m_9:'Syy',m_10:'Lok',m_11:'Mar',m_12:'Jou',p_we:'Tänä viikonloppuna',p_nw:'Ensi viikolla',p_tm:'Tässä kuussa',p_nm:'Ensi kuussa',title:'Matkasuodattimet',desc:'Aseta matkakumppanin kriteerit.',reset:'Nollaa',dest:'Kohde',dest_ph:'Hae kaupunkia...',search_res:'Tulokset',pop_city:'Suositut kaupungit',apply_as_is:' Hae',date:'Päivämäärä',sel_start:'Lähtöpäivä',sel_end:'Paluupäivä',year:' ',month:' ',day:'',size:'Henkilömäärä',all:'Ei väliä',s_6_more:'6+',unit_p:' hlö.',apply:'Käytä ',unit_f:'',view_all:'Kaikki ryhmät' },
    gdf: { activity:'Aktiviteetti',tour:'Kiertomatka',food:'Ravintola',cafe:'Kahvila',club:'Klubi',any:'Kaikki',gender:'Koostumus',g_2m2f:'2M2N',g_3m1f:'3M1N',g_1m3f:'1M3N',g_all_m:'Vain miehet',g_all_f:'Vain naiset',lang:'Kieli',l_any:'Ei väliä',l_any_desc:'Kaikki kielet',l_ko:'Korean',l_ko_desc:'Pääasiassa korean',l_for:'Ulkomainen',l_for_desc:'Englanti/ulkomainen',l_mix:'Sekattu',l_mix_desc:'Monikansallinen',vibe:'Tunnelma',v_any_desc:'Mikä tahansa',v_cas:'Rento',v_cas_desc:'Casual',v_party:'Juhlat',v_party_desc:'Juhlitaan!',v_ser:'Vakava',v_ser_desc:'Tavoitteellinen',title:'Ryhmäsuodattimet',desc:'Aseta kriteerit.',reset:'Nollaa',chk:'Kirjaudu myös',cur:'Ryhmät: ',based:'',apply:'Käytä ',unit:'',all:'Kaikki ryhmät' }
  }
};

const entries = Object.entries(langs).map(([lang, val]) => `  ${lang}: ${JSON.stringify(val)}`).join(',\n');
c = c.slice(0, -2) + ',\n' + entries + '\n};\n';
fs.writeFileSync(fp, c, 'utf8');
console.log('Done. Languages added:', Object.keys(langs).join(', '));
console.log('New size:', fs.statSync(fp).size, 'bytes');
