// add_filter_langs.cjs
const fs = require('fs');
const fp = 'src/i18n/filterLocales.ts';
let c = fs.readFileSync(fp, 'utf8').trimEnd();
if (!c.endsWith('};')) { console.error('Unexpected ending:', c.slice(-30)); process.exit(1); }

const langs = {
  fr: {
    gf: { c_tokyo:'Tokyo',c_seoul:'Seoul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapour',c_osaka:'Osaka',c_taipei:'Taipei',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelone',c_paris:'Paris',n_jp:'Japon',n_kr:'Corée',n_th:'Thaïlande',n_id:'Indonésie',n_vn:'Vietnam',n_sg:'Singapour',n_tw:'Taïwan',n_ph:'Philippines',n_es:'Espagne',n_fr:'France',s_2:'2 pers.',s_3:'3 pers.',s_4:'4 pers.',s_5:'5 pers.',s_6:'6 pers.',w_sun:'Dim',w_mon:'Lun',w_tue:'Mar',w_wed:'Mer',w_thu:'Jeu',w_fri:'Ven',w_sat:'Sam',m_1:'Jan',m_2:'Fév',m_3:'Mar',m_4:'Avr',m_5:'Mai',m_6:'Jun',m_7:'Jul',m_8:'Aoû',m_9:'Sep',m_10:'Oct',m_11:'Nov',m_12:'Déc',p_we:'Ce week-end',p_nw:'Semaine prochaine',p_tm:'Ce mois',p_nm:'Mois prochain',title:'Filtres voyage',desc:'Définissez les critères.',reset:'Réinitialiser',dest:'Destination',dest_ph:'Chercher une ville...',search_res:'Résultats',pop_city:'Villes populaires',apply_as_is:' Rechercher',date:'Date',sel_start:'Départ',sel_end:'Retour',year:' ',month:' ',day:'',size:'Nombre de personnes',all:'Peu importe',s_6_more:'6+',unit_p:'',apply:'Appliquer ',unit_f:'',view_all:'Tous les groupes' },
    gdf: { activity:'Activité',tour:'Visite',food:'Resto',cafe:'Café',club:'Club',any:'Tout',gender:'Composition',g_2m2f:'2H2F',g_3m1f:'3H1F',g_1m3f:'1H3F',g_all_m:'Hommes seuls',g_all_f:'Femmes seules',lang:'Langue',l_any:'Peu importe',l_any_desc:'Toutes langues',l_ko:'Coréen',l_ko_desc:'Coréen princ.',l_for:'Étranger',l_for_desc:'Anglais/étranger',l_mix:'Mixte',l_mix_desc:'Multi-national',vibe:'Ambiance',v_any_desc:'Toutes ambiances',v_cas:'Détendu',v_cas_desc:'Casual',v_party:'Fête',v_party_desc:'On s\'amuse!',v_ser:'Sérieux',v_ser_desc:'Voyage ciblé',title:'Filtres groupe',desc:'Définissez les critères.',reset:'Réinitialiser',chk:'Check-in aussi',cur:'Groupes à ',based:'',apply:'Appliquer ',unit:'',all:'Tous les groupes' }
  },
  de: {
    gf: { c_tokyo:'Tokio',c_seoul:'Seoul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapur',c_osaka:'Osaka',c_taipei:'Taipeh',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Paris',n_jp:'Japan',n_kr:'Korea',n_th:'Thailand',n_id:'Indonesien',n_vn:'Vietnam',n_sg:'Singapur',n_tw:'Taiwan',n_ph:'Philippinen',n_es:'Spanien',n_fr:'Frankreich',s_2:'2 Pers.',s_3:'3 Pers.',s_4:'4 Pers.',s_5:'5 Pers.',s_6:'6 Pers.',w_sun:'So',w_mon:'Mo',w_tue:'Di',w_wed:'Mi',w_thu:'Do',w_fri:'Fr',w_sat:'Sa',m_1:'Jan',m_2:'Feb',m_3:'Mär',m_4:'Apr',m_5:'Mai',m_6:'Jun',m_7:'Jul',m_8:'Aug',m_9:'Sep',m_10:'Okt',m_11:'Nov',m_12:'Dez',p_we:'Dieses Wochenende',p_nw:'Nächste Woche',p_tm:'Diesen Monat',p_nm:'Nächsten Monat',title:'Reisefilter',desc:'Kriterien festlegen.',reset:'Zurücksetzen',dest:'Reiseziel',dest_ph:'Stadt suchen...',search_res:'Suchergebnisse',pop_city:'Beliebte Städte',apply_as_is:' Suchen',date:'Datum',sel_start:'Abreise',sel_end:'Rückkehr',year:' ',month:' ',day:'',size:'Personenzahl',all:'Egal',s_6_more:'6+',unit_p:'',apply:'Anwenden ',unit_f:'',view_all:'Alle Gruppen' },
    gdf: { activity:'Aktivitätsart',tour:'Tour',food:'Restaurant',cafe:'Café',club:'Club',any:'Alle',gender:'Zusammensetzung',g_2m2f:'2M2F',g_3m1f:'3M1F',g_1m3f:'1M3F',g_all_m:'Nur Männer',g_all_f:'Nur Frauen',lang:'Sprache',l_any:'Egal',l_any_desc:'Alle Sprachen',l_ko:'Koreanisch',l_ko_desc:'Hauptsächlich Koreanisch',l_for:'Ausländisch',l_for_desc:'Englisch/Fremdsprache',l_mix:'Gemischt',l_mix_desc:'Multinational',vibe:'Atmosphäre',v_any_desc:'Alle Atmosphären',v_cas:'Entspannt',v_cas_desc:'Casual',v_party:'Party',v_party_desc:'Party!',v_ser:'Ernsthaft',v_ser_desc:'Zielorientiert',title:'Gruppenfilter',desc:'Kriterien festlegen.',reset:'Zurücksetzen',chk:'Auch einchecken',cur:'Gruppen in ',based:'',apply:'Anwenden ',unit:'',all:'Alle Gruppen' }
  },
  pt: {
    gf: { c_tokyo:'Tóquio',c_seoul:'Seul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapura',c_osaka:'Osaka',c_taipei:'Taipé',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcelona',c_paris:'Paris',n_jp:'Japão',n_kr:'Coreia',n_th:'Tailândia',n_id:'Indonésia',n_vn:'Vietnã',n_sg:'Singapura',n_tw:'Taiwan',n_ph:'Filipinas',n_es:'Espanha',n_fr:'França',s_2:'2 pess.',s_3:'3 pess.',s_4:'4 pess.',s_5:'5 pess.',s_6:'6 pess.',w_sun:'Dom',w_mon:'Seg',w_tue:'Ter',w_wed:'Qua',w_thu:'Qui',w_fri:'Sex',w_sat:'Sáb',m_1:'Jan',m_2:'Fev',m_3:'Mar',m_4:'Abr',m_5:'Mai',m_6:'Jun',m_7:'Jul',m_8:'Ago',m_9:'Set',m_10:'Out',m_11:'Nov',m_12:'Dez',p_we:'Este fim de semana',p_nw:'Próxima semana',p_tm:'Este mês',p_nm:'Próximo mês',title:'Filtros viagem',desc:'Defina os critérios.',reset:'Redefinir',dest:'Destino',dest_ph:'Buscar cidade...',search_res:'Resultados',pop_city:'Cidades populares',apply_as_is:' Buscar',date:'Data',sel_start:'Partida',sel_end:'Retorno',year:' ',month:' ',day:'',size:'Nº de pessoas',all:'Tanto faz',s_6_more:'6+',unit_p:'',apply:'Aplicar ',unit_f:'',view_all:'Ver todos os grupos' },
    gdf: { activity:'Atividade',tour:'Tour',food:'Restaurante',cafe:'Café',club:'Clube',any:'Tudo',gender:'Composição',g_2m2f:'2H2M',g_3m1f:'3H1M',g_1m3f:'1H3M',g_all_m:'Só homens',g_all_f:'Só mulheres',lang:'Idioma',l_any:'Tanto faz',l_any_desc:'Todos os idiomas',l_ko:'Coreano',l_ko_desc:'Princ. coreano',l_for:'Estrangeiro',l_for_desc:'Inglês/estrangeiro',l_mix:'Misto',l_mix_desc:'Multinacional',vibe:'Clima',v_any_desc:'Qualquer',v_cas:'Descontraído',v_cas_desc:'Casual',v_party:'Festa',v_party_desc:'Festa!',v_ser:'Sério',v_ser_desc:'Com propósito',title:'Filtros grupo',desc:'Defina os critérios.',reset:'Redefinir',chk:'Check-in também',cur:'Grupos em ',based:'',apply:'Aplicar ',unit:'',all:'Ver todos os grupos' }
  },
  ru: {
    gf: { c_tokyo:'Токио',c_seoul:'Сеул',c_bangkok:'Бангкок',c_bali:'Бали',c_danang:'Дананг',c_sg:'Сингапур',c_osaka:'Осака',c_taipei:'Тайбэй',c_chiangmai:'Чиангмай',c_cebu:'Себу',c_bcn:'Барселона',c_paris:'Париж',n_jp:'Япония',n_kr:'Корея',n_th:'Таиланд',n_id:'Индонезия',n_vn:'Вьетнам',n_sg:'Сингапур',n_tw:'Тайвань',n_ph:'Филиппины',n_es:'Испания',n_fr:'Франция',s_2:'2 чел.',s_3:'3 чел.',s_4:'4 чел.',s_5:'5 чел.',s_6:'6 чел.',w_sun:'Вс',w_mon:'Пн',w_tue:'Вт',w_wed:'Ср',w_thu:'Чт',w_fri:'Пт',w_sat:'Сб',m_1:'Янв',m_2:'Фев',m_3:'Мар',m_4:'Апр',m_5:'Май',m_6:'Июн',m_7:'Июл',m_8:'Авг',m_9:'Сен',m_10:'Окт',m_11:'Ноя',m_12:'Дек',p_we:'Эти выходные',p_nw:'Следующая неделя',p_tm:'Этот месяц',p_nm:'Следующий месяц',title:'Фильтры поездки',desc:'Задайте критерии.',reset:'Сбросить',dest:'Направление',dest_ph:'Поиск города...',search_res:'Результаты',pop_city:'Попул. города',apply_as_is:' Найти',date:'Дата',sel_start:'Отправление',sel_end:'Возвращение',year:' г.',month:' ',day:'',size:'Кол-во чел.',all:'Не важно',s_6_more:'6+',unit_p:' чел.',apply:'Применить ',unit_f:'',view_all:'Все группы' },
    gdf: { activity:'Активность',tour:'Тур',food:'Ресторан',cafe:'Кафе',club:'Клуб',any:'Любой',gender:'Пол',g_2m2f:'2М2Ж',g_3m1f:'3М1Ж',g_1m3f:'1М3Ж',g_all_m:'Только мужчины',g_all_f:'Только женщины',lang:'Язык',l_any:'Не важно',l_any_desc:'Все языки',l_ko:'Корейский',l_ko_desc:'Преим. корейский',l_for:'Иностранный',l_for_desc:'Английский',l_mix:'Смешанный',l_mix_desc:'Международный',vibe:'Атмосфера',v_any_desc:'Любая',v_cas:'Расслабленная',v_cas_desc:'Casual',v_party:'Вечеринка',v_party_desc:'Повеселимся!',v_ser:'Серьёзная',v_ser_desc:'Целенаправленное',title:'Фильтры группы',desc:'Задайте критерии.',reset:'Сбросить',chk:'Check-in тоже',cur:'Группы в ',based:'',apply:'Применить ',unit:'',all:'Все группы' }
  },
  ar: {
    gf: { c_tokyo:'طوكيو',c_seoul:'سيول',c_bangkok:'بانكوك',c_bali:'بالي',c_danang:'دا نانغ',c_sg:'سنغافورة',c_osaka:'أوساكا',c_taipei:'تايبيه',c_chiangmai:'شيانغ ماي',c_cebu:'سيبو',c_bcn:'برشلونة',c_paris:'باريس',n_jp:'اليابان',n_kr:'كوريا',n_th:'تايلاند',n_id:'إندونيسيا',n_vn:'فيتنام',n_sg:'سنغافورة',n_tw:'تايوان',n_ph:'الفلبين',n_es:'إسبانيا',n_fr:'فرنسا',s_2:'شخصان',s_3:'3',s_4:'4',s_5:'5',s_6:'6',w_sun:'أحد',w_mon:'اثن',w_tue:'ثلا',w_wed:'أرب',w_thu:'خمس',w_fri:'جمع',w_sat:'سبت',m_1:'يناير',m_2:'فبراير',m_3:'مارس',m_4:'أبريل',m_5:'مايو',m_6:'يونيو',m_7:'يوليو',m_8:'أغسطس',m_9:'سبتمبر',m_10:'أكتوبر',m_11:'نوفمبر',m_12:'ديسمبر',p_we:'هذا الأسبوع',p_nw:'الأسبوع القادم',p_tm:'هذا الشهر',p_nm:'الشهر القادم',title:'فلاتر السفر',desc:'حدد معايير رفيقك.',reset:'إعادة تعيين',dest:'الوجهة',dest_ph:'ابحث عن مدينة...',search_res:'النتائج',pop_city:'مدن شعبية',apply_as_is:' بحث',date:'التاريخ',sel_start:'المغادرة',sel_end:'العودة',year:' ',month:' ',day:'',size:'عدد الأشخاص',all:'لا يهم',s_6_more:'+6',unit_p:'',apply:'تطبيق ',unit_f:'',view_all:'جميع المجموعات' },
    gdf: { activity:'النشاط',tour:'جولة',food:'مطعم',cafe:'مقهى',club:'نادي',any:'الكل',gender:'النوع',g_2m2f:'2ذ2أ',g_3m1f:'3ذ1أ',g_1m3f:'1ذ3أ',g_all_m:'رجال فقط',g_all_f:'نساء فقط',lang:'اللغة',l_any:'لا يهم',l_any_desc:'كل اللغات',l_ko:'كوري',l_ko_desc:'كوري بشكل رئيسي',l_for:'أجنبي',l_for_desc:'إنجليزي/أجنبي',l_mix:'مختلط',l_mix_desc:'متعدد الجنسيات',vibe:'الأجواء',v_any_desc:'أي أجواء',v_cas:'مريح',v_cas_desc:'كاجوال',v_party:'حفلة',v_party_desc:'متعة!',v_ser:'جدي',v_ser_desc:'هادف',title:'فلاتر المجموعة',desc:'حدد معايير رفيقك.',reset:'إعادة تعيين',chk:'تسجيل وصول أيضاً',cur:'مجموعات في ',based:'',apply:'تطبيق ',unit:'',all:'جميع المجموعات' }
  },
  hi: {
    gf: { c_tokyo:'टोक्यो',c_seoul:'सियोल',c_bangkok:'बैंकॉक',c_bali:'बाली',c_danang:'दा नांग',c_sg:'सिंगापुर',c_osaka:'ओसाका',c_taipei:'ताइपे',c_chiangmai:'चियांग माई',c_cebu:'सेबू',c_bcn:'बार्सिलोना',c_paris:'पेरिस',n_jp:'जापान',n_kr:'कोरिया',n_th:'थाईलैंड',n_id:'इंडोनेशिया',n_vn:'वियतनाम',n_sg:'सिंगापुर',n_tw:'ताइवान',n_ph:'फिलीपींस',n_es:'स्पेन',n_fr:'फ्रांस',s_2:'2',s_3:'3',s_4:'4',s_5:'5',s_6:'6',w_sun:'रवि',w_mon:'सोम',w_tue:'मंग',w_wed:'बुध',w_thu:'गुरु',w_fri:'शुक्र',w_sat:'शनि',m_1:'जन',m_2:'फर',m_3:'मार्च',m_4:'अप्रैल',m_5:'मई',m_6:'जून',m_7:'जुल',m_8:'अग',m_9:'सित',m_10:'अक्ट',m_11:'नव',m_12:'दिस',p_we:'इस सप्ताहांत',p_nw:'अगला सप्ताह',p_tm:'इस महीने',p_nm:'अगले महीने',title:'यात्रा फ़िल्टर',desc:'साथी की शर्तें।',reset:'रीसेट',dest:'गंतव्य',dest_ph:'शहर खोजें...',search_res:'परिणाम',pop_city:'लोकप्रिय शहर',apply_as_is:' खोजें',date:'तारीख',sel_start:'प्रस्थान',sel_end:'वापसी',year:' ',month:' ',day:'',size:'लोगों की संख्या',all:'कोई भी',s_6_more:'6+',unit_p:'',apply:'लागू करें ',unit_f:'',view_all:'सभी समूह' },
    gdf: { activity:'गतिविधि',tour:'टूर',food:'रेस्तरां',cafe:'कैफे',club:'क्लब',any:'सभी',gender:'लिंग',g_2m2f:'2पु2म',g_3m1f:'3पु1म',g_1m3f:'1पु3म',g_all_m:'केवल पुरुष',g_all_f:'केवल महिला',lang:'भाषा',l_any:'कोई भी',l_any_desc:'सभी भाषाएं',l_ko:'कोरियाई',l_ko_desc:'मुख्यतः कोरियाई',l_for:'विदेशी',l_for_desc:'अंग्रेजी/विदेशी',l_mix:'मिश्रित',l_mix_desc:'बहुराष्ट्रीय',vibe:'माहौल',v_any_desc:'कोई भी',v_cas:'आरामदायक',v_cas_desc:'कैजुअल',v_party:'पार्टी',v_party_desc:'मज़ा!',v_ser:'गंभीर',v_ser_desc:'लक्ष्य आधारित',title:'समूह फ़िल्टर',desc:'साथी की शर्तें।',reset:'रीसेट',chk:'चेक-इन भी',cur:'समूह ',based:' में',apply:'लागू करें ',unit:'',all:'सभी समूह' }
  },
  tr: {
    gf: { c_tokyo:'Tokyo',c_seoul:'Seul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapur',c_osaka:'Osaka',c_taipei:'Taipei',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barselona',c_paris:'Paris',n_jp:'Japonya',n_kr:'Güney Kore',n_th:'Tayland',n_id:'Endonezya',n_vn:'Vietnam',n_sg:'Singapur',n_tw:'Tayvan',n_ph:'Filipinler',n_es:'İspanya',n_fr:'Fransa',s_2:'2 kişi',s_3:'3 kişi',s_4:'4 kişi',s_5:'5 kişi',s_6:'6 kişi',w_sun:'Paz',w_mon:'Pts',w_tue:'Sal',w_wed:'Çar',w_thu:'Per',w_fri:'Cum',w_sat:'Cts',m_1:'Oca',m_2:'Şub',m_3:'Mar',m_4:'Nis',m_5:'May',m_6:'Haz',m_7:'Tem',m_8:'Ağu',m_9:'Eyl',m_10:'Eki',m_11:'Kas',m_12:'Ara',p_we:'Bu hafta sonu',p_nw:'Gelecek hafta',p_tm:'Bu ay',p_nm:'Gelecek ay',title:'Seyahat filtreleri',desc:'Arkadaş kriterlerini belirle.',reset:'Sıfırla',dest:'Hedef',dest_ph:'Şehir ara...',search_res:'Sonuçlar',pop_city:'Popüler şehirler',apply_as_is:' Ara',date:'Tarih',sel_start:'Kalkış',sel_end:'Dönüş',year:' ',month:' ',day:'',size:'Kişi sayısı',all:'Fark etmez',s_6_more:'6+',unit_p:' kişi',apply:'Uygula ',unit_f:'',view_all:'Tüm grupları gör' },
    gdf: { activity:'Aktivite',tour:'Tur',food:'Restoran',cafe:'Kafe',club:'Kulüp',any:'Hepsi',gender:'Cinsiyet',g_2m2f:'2E2K',g_3m1f:'3E1K',g_1m3f:'1E3K',g_all_m:'Sadece erkek',g_all_f:'Sadece kadın',lang:'Dil',l_any:'Fark etmez',l_any_desc:'Tüm diller',l_ko:'Korece',l_ko_desc:'Ağ. Korece',l_for:'Yabancı',l_for_desc:'İngilizce/Yabancı',l_mix:'Karma',l_mix_desc:'Çok uluslu',vibe:'Atmosfer',v_any_desc:'Her atmosfer',v_cas:'Rahat',v_cas_desc:'Casual',v_party:'Parti',v_party_desc:'Eğlence!',v_ser:'Ciddi',v_ser_desc:'Amaçlı',title:'Grup filtreleri',desc:'Arkadaş kriterleri.',reset:'Sıfırla',chk:'Check-in de',cur:'Gruplar: ',based:'',apply:'Uygula ',unit:'',all:'Tüm gruplar' }
  },
  it: {
    gf: { c_tokyo:'Tokyo',c_seoul:'Seul',c_bangkok:'Bangkok',c_bali:'Bali',c_danang:'Da Nang',c_sg:'Singapore',c_osaka:'Osaka',c_taipei:'Taipei',c_chiangmai:'Chiang Mai',c_cebu:'Cebu',c_bcn:'Barcellona',c_paris:'Parigi',n_jp:'Giappone',n_kr:'Corea',n_th:'Tailandia',n_id:'Indonesia',n_vn:'Vietnam',n_sg:'Singapore',n_tw:'Taiwan',n_ph:'Filippine',n_es:'Spagna',n_fr:'Francia',s_2:'2 pers.',s_3:'3 pers.',s_4:'4 pers.',s_5:'5 pers.',s_6:'6 pers.',w_sun:'Dom',w_mon:'Lun',w_tue:'Mar',w_wed:'Mer',w_thu:'Gio',w_fri:'Ven',w_sat:'Sab',m_1:'Gen',m_2:'Feb',m_3:'Mar',m_4:'Apr',m_5:'Mag',m_6:'Giu',m_7:'Lug',m_8:'Ago',m_9:'Set',m_10:'Ott',m_11:'Nov',m_12:'Dic',p_we:'Questo weekend',p_nw:'Prossima settimana',p_tm:'Questo mese',p_nm:'Prossimo mese',title:'Filtri viaggio',desc:'Imposta i criteri.',reset:'Reimposta',dest:'Destinazione',dest_ph:'Cerca città...',search_res:'Risultati',pop_city:'Città popolari',apply_as_is:' Cerca',date:'Data',sel_start:'Partenza',sel_end:'Ritorno',year:' ',month:' ',day:'',size:'Numero persone',all:'Non importa',s_6_more:'6+',unit_p:'',apply:'Applica ',unit_f:'',view_all:'Tutti i gruppi' },
    gdf: { activity:'Attività',tour:'Tour',food:'Ristorante',cafe:'Caffè',club:'Club',any:'Tutto',gender:'Genere',g_2m2f:'2U2D',g_3m1f:'3U1D',g_1m3f:'1U3D',g_all_m:'Solo uomini',g_all_f:'Solo donne',lang:'Lingua',l_any:'Non importa',l_any_desc:'Tutte le lingue',l_ko:'Coreano',l_ko_desc:'Prev. coreano',l_for:'Straniero',l_for_desc:'Inglese/straniero',l_mix:'Misto',l_mix_desc:'Multinazionale',vibe:'Atmosfera',v_any_desc:'Qualsiasi',v_cas:'Rilassato',v_cas_desc:'Casual',v_party:'Festa',v_party_desc:'Divertiamoci!',v_ser:'Serio',v_ser_desc:'Mirato',title:'Filtri gruppo',desc:'Criteri compagno.',reset:'Reimposta',chk:'Check-in anche',cur:'Gruppi a ',based:'',apply:'Applica ',unit:'',all:'Tutti i gruppi' }
  }
};

const entries = Object.entries(langs).map(([lang, val]) => `  ${lang}: ${JSON.stringify(val)}`).join(',\n');
c = c.slice(0, -2) + ',\n' + entries + '\n};\n';
fs.writeFileSync(fp, c, 'utf8');
console.log('Done. Languages added:', Object.keys(langs).join(', '));
console.log('New size:', fs.statSync(fp).size, 'bytes');
