/**
 * fix_en_ts.mjs
 * Fixes en.ts generated by build_en.mjs:
 * 1. Replaces literal newlines inside string values with \n escape sequences
 * 2. Fixes remaining Korean values for key translation strings
 */
import fs from 'fs';

let en = fs.readFileSync('./src/i18n/locales/en.ts', 'utf8');

// Fix literal newlines inside string values
// Pattern: find "key": "...NEWLINE..." and replace with "key": "...\n..."
// We need to be careful to only fix newlines INSIDE string values, not between key-value pairs

let fixed = '';
let inString = false;
let escaped = false;
let i = 0;

while (i < en.length) {
  const ch = en[i];
  
  if (escaped) {
    fixed += ch;
    escaped = false;
    i++;
    continue;
  }
  
  if (ch === '\\' && inString) {
    escaped = true;
    fixed += ch;
    i++;
    continue;
  }
  
  if (ch === '"') {
    inString = !inString;
    fixed += ch;
    i++;
    continue;
  }
  
  if (inString && ch === '\n') {
    // Replace literal newline inside string with \n escape
    fixed += '\\n';
    i++;
    continue;
  }
  
  if (inString && ch === '\r') {
    // Skip carriage return inside string
    i++;
    continue;
  }
  
  fixed += ch;
  i++;
}

// Also fix Korean values for critical keys that should be English
// p-keys that are still Korean
const koToEn = {
  '"p7": "미인증 ({{count}})"': '"p7": "Unauthenticated ({{count}})"',
  '"p8": "인증됨 ({{count}})"': '"p8": "Verified ({{count}})"',
  '"p9": "정지됨 ({{count}})"': '"p9": "Suspended ({{count}})"',
  '"p10": "{{name}} 신분증 인증 승인"': '"p10": "{{name}} ID verification approved"',
  '"p32": "어떤 점이"': '"p32": "What"',
  '"p33": "좋으셨나요?"': '"p33": "was it good?"',
  '"p34": "아쉬우셨나요?"': '"p34": "could be better?"',
  '"p35": "오늘 {{val}}번 남았습니다."': '"p35": "{{val}} times remaining today."',
};

for (const [ko, en_val] of Object.entries(koToEn)) {
  fixed = fixed.replace(ko, en_val);
}

fs.writeFileSync('./src/i18n/locales/en.ts', fixed, 'utf8');
console.log('en.ts fixed. Size:', fixed.length, 'bytes');

// Count remaining Korean
const koMatches = fixed.match(/:\s*"[^"]*[\uAC00-\uD7A3][^"]*"/g) || [];
console.log('Remaining Korean strings in en.ts:', koMatches.length);
console.log('Sample:', koMatches.slice(0, 5).map(m => m.trim().substring(0, 60)).join('\n'));
