import { readFileSync, writeFileSync } from 'fs';

const FILE = 'c:\\Users\\ujin1\\Desktop\\migoapp\\src\\i18n\\retentionLocales.ts';

// All new setup keys per language
const translations = {
  ko: {
    "setup.step0.title": "프로필 사진",
    "setup.step0.sub": "첫인상이 중요해요",
    "setup.step1.title": "여행 스타일",
    "setup.step1.sub": "어떤 여행을 하시나요?",
    "setup.step2.title": "어떤 여행자인가요?",
    "setup.step2.sub": "선택사항",
    "setup.label.photo": "프로필 사진",
    "setup.label.main": "대표",
    "setup.label.add": "추가",
    "setup.type.traveler": "여행자",
    "setup.type.local": "로컬 가이드",
    "setup.label.nickname": "닉네임",
    "setup.placeholder.nickname": "예: MigoTraveler",
    "setup.label.nationality": "국적",
    "setup.label.selected": "선택됨",
    "setup.placeholder.searchCountry": "국가 검색...",
    "setup.label.bio": "자기소개",
    "setup.optional": "선택",
    "setup.placeholder.bio": "어떤 여행을 좋아하세요? 간단히 소개해 주세요 ✈️",
    "setup.label.travelStyle": "여행 스타일",
    "setup.label.regions": "선호 여행지",
    "setup.multiSelect": "복수 선택",
    "setup.label.personality": "여행 성향",
    "setup.label.preview": "미리보기",
    "setup.placeholder.noBio": "소개 없음",
    "setup.btn.saving": "저장 중...",
    "setup.btn.complete": "프로필 완성",
    "setup.btn.next": "다음",
    "setup.btn.mbtiNote": "성격/MBTI는 나중에 언제든지 변경 가능해요 👌",
    "setup.validate.photo": "📸 사진을 1장 이상 추가해 주세요",
    "setup.validate.nickname": "닉네임을 입력해 주세요",
    "setup.validate.nationality": "국적을 선택해 주세요",
    "setup.validate.style": "여행 스타일을 1개 이상 선택해 주세요",
    "setup.error.uploadFailed": "프로필 사진 업로드에 실패했습니다. 이미지 파일 규격 또는 네트워크 상태를 확인해 주세요.",
    "setup.error.save": "저장 실패",
    "setup.error.generic": "오류가 발생했습니다. 다시 시도해 주세요.",
    "setup.done.title": "🎉 프로필 완성!",
    "setup.done.desc": "Migo에 오신 걸 환영해요 ✈️",
    "setup.style.backpack": "백패킹 🎒",
    "setup.style.luxury": "럭셔리 ✈️",
    "setup.style.nature": "자연/하이킹 🏔️",
    "setup.style.food": "맛집 투어 🍜",
    "setup.style.culture": "문화/역사 🏛️",
    "setup.style.beach": "비치/리조트 🏖️",
    "setup.style.photo": "사진 촬영 📸",
    "setup.style.nightlife": "나이트라이프 🌙",
    "setup.style.shopping": "쇼핑 🛍️",
    "setup.style.healing": "힐링/요가 🧘",
    "setup.style.local": "로컬 체험 🎭",
    "setup.style.drive": "로드 트립 🚗",
    "setup.region.sea": "동남아시아 🌴",
    "setup.region.europe": "유럽 🏰",
    "setup.region.japan": "일본 🗾",
    "setup.region.usa": "미국/캐나다 🗽",
    "setup.region.latam": "중남미 🌎",
    "setup.region.oceania": "오세아니아 🦘",
    "setup.region.mideast": "중동/아프리카 🌍",
    "setup.region.domestic": "국내 여행 🇰🇷",
    "setup.region.china": "중국/대만 🐉",
    "setup.region.india": "인도 🕌",
    "setup.personality.planner": "계획형",
    "setup.personality.free": "자유로운 영혼",
    "setup.personality.social": "소셜 나비",
    "setup.personality.solo": "솔로 여행자",
    "setup.personality.photo": "사진 수집가",
    "setup.personality.food": "미식 탐험가",
  },
  en: {
    "setup.step0.title": "Profile Photo",
    "setup.step0.sub": "First impressions matter",
    "setup.step1.title": "Travel Style",
    "setup.step1.sub": "How do you travel?",
    "setup.step2.title": "What kind of traveler?",
    "setup.step2.sub": "Optional",
    "setup.label.photo": "Profile Photo",
    "setup.label.main": "Main",
    "setup.label.add": "Add",
    "setup.type.traveler": "Traveler",
    "setup.type.local": "Local Guide",
    "setup.label.nickname": "Nickname",
    "setup.placeholder.nickname": "e.g. MigoTraveler",
    "setup.label.nationality": "Nationality",
    "setup.label.selected": "Selected",
    "setup.placeholder.searchCountry": "Search country...",
    "setup.label.bio": "About Me",
    "setup.optional": "Optional",
    "setup.placeholder.bio": "What kind of travel do you enjoy? Introduce yourself briefly ✈️",
    "setup.label.travelStyle": "Travel Style",
    "setup.label.regions": "Preferred Destinations",
    "setup.multiSelect": "multiple",
    "setup.label.personality": "Travel Personality",
    "setup.label.preview": "Preview",
    "setup.placeholder.noBio": "No introduction",
    "setup.btn.saving": "Saving...",
    "setup.btn.complete": "Complete Profile",
    "setup.btn.next": "Next",
    "setup.btn.mbtiNote": "Personality/MBTI can be changed anytime later 👌",
    "setup.validate.photo": "📸 Please add at least 1 photo",
    "setup.validate.nickname": "Please enter a nickname",
    "setup.validate.nationality": "Please select your nationality",
    "setup.validate.style": "Please choose at least 1 travel style",
    "setup.error.uploadFailed": "Failed to upload profile photo. Please check the image file format or network status.",
    "setup.error.save": "Save failed",
    "setup.error.generic": "An error occurred. Please try again.",
    "setup.done.title": "🎉 Profile complete!",
    "setup.done.desc": "Welcome to Migo ✈️",
    "setup.style.backpack": "Backpacking 🎒",
    "setup.style.luxury": "Luxury ✈️",
    "setup.style.nature": "Nature/Hiking 🏔️",
    "setup.style.food": "Food Tour 🍜",
    "setup.style.culture": "Culture/History 🏛️",
    "setup.style.beach": "Beach/Resort 🏖️",
    "setup.style.photo": "Photography 📸",
    "setup.style.nightlife": "Nightlife 🌙",
    "setup.style.shopping": "Shopping 🛍️",
    "setup.style.healing": "Healing/Yoga 🧘",
    "setup.style.local": "Local Experience 🎭",
    "setup.style.drive": "Road Trip 🚗",
    "setup.region.sea": "Southeast Asia 🌴",
    "setup.region.europe": "Europe 🏰",
    "setup.region.japan": "Japan 🗾",
    "setup.region.usa": "USA/Canada 🗽",
    "setup.region.latam": "Latin America 🌎",
    "setup.region.oceania": "Oceania 🦘",
    "setup.region.mideast": "Middle East/Africa 🌍",
    "setup.region.domestic": "Domestic 🇰🇷",
    "setup.region.china": "China/Taiwan 🐉",
    "setup.region.india": "India 🕌",
    "setup.personality.planner": "Planner",
    "setup.personality.free": "Free Spirit",
    "setup.personality.social": "Social Butterfly",
    "setup.personality.solo": "Solo Traveler",
    "setup.personality.photo": "Photo Collector",
    "setup.personality.food": "Foodie Explorer",
  },
  ja: {
    "setup.step0.title": "プロフィール写真",
    "setup.step0.sub": "第一印象が大切です",
    "setup.step1.title": "旅行スタイル",
    "setup.step1.sub": "どんな旅をしますか？",
    "setup.step2.title": "どんな旅行者？",
    "setup.step2.sub": "任意",
    "setup.label.photo": "プロフィール写真",
    "setup.label.main": "メイン",
    "setup.label.add": "追加",
    "setup.type.traveler": "旅行者",
    "setup.type.local": "地元ガイド",
    "setup.label.nickname": "ニックネーム",
    "setup.placeholder.nickname": "例：MigoTraveler",
    "setup.label.nationality": "国籍",
    "setup.label.selected": "選択済み",
    "setup.placeholder.searchCountry": "国を検索...",
    "setup.label.bio": "自己紹介",
    "setup.optional": "任意",
    "setup.placeholder.bio": "どんな旅が好きですか？簡単に自己紹介してください ✈️",
    "setup.label.travelStyle": "旅行スタイル",
    "setup.label.regions": "お気に入りの旅先",
    "setup.multiSelect": "複数選択",
    "setup.label.personality": "旅の性格",
    "setup.label.preview": "プレビュー",
    "setup.placeholder.noBio": "紹介なし",
    "setup.btn.saving": "保存中...",
    "setup.btn.complete": "プロフィール完成",
    "setup.btn.next": "次へ",
    "setup.btn.mbtiNote": "性格/MBTIはいつでも変更できます 👌",
    "setup.validate.photo": "📸 写真を1枚以上追加してください",
    "setup.validate.nickname": "ニックネームを入力してください",
    "setup.validate.nationality": "国籍を選択してください",
    "setup.validate.style": "旅行スタイルを1つ以上選んでください",
    "setup.error.uploadFailed": "プロフィール写真のアップロードに失敗しました。画像ファイル形式またはネットワーク状態を確認してください。",
    "setup.error.save": "保存に失敗しました",
    "setup.error.generic": "エラーが発生しました。もう一度お試しください。",
    "setup.done.title": "🎉 プロフィール完成！",
    "setup.done.desc": "Migoへようこそ ✈️",
    "setup.style.backpack": "バックパッキング 🎒",
    "setup.style.luxury": "ラグジュアリー ✈️",
    "setup.style.nature": "自然/ハイキング 🏔️",
    "setup.style.food": "グルメツアー 🍜",
    "setup.style.culture": "文化/歴史 🏛️",
    "setup.style.beach": "ビーチ/リゾート 🏖️",
    "setup.style.photo": "写真撮影 📸",
    "setup.style.nightlife": "ナイトライフ 🌙",
    "setup.style.shopping": "ショッピング 🛍️",
    "setup.style.healing": "ヒーリング/ヨガ 🧘",
    "setup.style.local": "ローカル体験 🎭",
    "setup.style.drive": "ロードトリップ 🚗",
    "setup.region.sea": "東南アジア 🌴",
    "setup.region.europe": "ヨーロッパ 🏰",
    "setup.region.japan": "日本 🗾",
    "setup.region.usa": "アメリカ/カナダ 🗽",
    "setup.region.latam": "中南米 🌎",
    "setup.region.oceania": "オセアニア 🦘",
    "setup.region.mideast": "中東/アフリカ 🌍",
    "setup.region.domestic": "国内旅行 🇰🇷",
    "setup.region.china": "中国/台湾 🐉",
    "setup.region.india": "インド 🕌",
    "setup.personality.planner": "計画型",
    "setup.personality.free": "自由な魂",
    "setup.personality.social": "ソーシャルバタフライ",
    "setup.personality.solo": "ソロトラベラー",
    "setup.personality.photo": "フォトコレクター",
    "setup.personality.food": "グルメ探検家",
  },
  zh: {
    "setup.step0.title": "头像",
    "setup.step0.sub": "第一印象很重要",
    "setup.step1.title": "旅行风格",
    "setup.step1.sub": "你怎么旅行？",
    "setup.step2.title": "你是什么样的旅行者？",
    "setup.step2.sub": "可选",
    "setup.label.photo": "头像",
    "setup.label.main": "主图",
    "setup.label.add": "添加",
    "setup.type.traveler": "旅行者",
    "setup.type.local": "当地向导",
    "setup.label.nickname": "昵称",
    "setup.placeholder.nickname": "例如：MigoTraveler",
    "setup.label.nationality": "国籍",
    "setup.label.selected": "已选择",
    "setup.placeholder.searchCountry": "搜索国家...",
    "setup.label.bio": "个人简介",
    "setup.optional": "可选",
    "setup.placeholder.bio": "你喜欢什么样的旅行？简单介绍一下自己吧 ✈️",
    "setup.label.travelStyle": "旅行风格",
    "setup.label.regions": "偏好目的地",
    "setup.multiSelect": "多选",
    "setup.label.personality": "旅行性格",
    "setup.label.preview": "预览",
    "setup.placeholder.noBio": "暂无介绍",
    "setup.btn.saving": "保存中...",
    "setup.btn.complete": "完成资料",
    "setup.btn.next": "下一步",
    "setup.btn.mbtiNote": "性格/MBTI可以随时更改 👌",
    "setup.validate.photo": "📸 请至少添加1张照片",
    "setup.validate.nickname": "请输入昵称",
    "setup.validate.nationality": "请选择国籍",
    "setup.validate.style": "请至少选择1种旅行风格",
    "setup.error.uploadFailed": "上传头像失败。请检查图片格式或网络状态。",
    "setup.error.save": "保存失败",
    "setup.error.generic": "发生错误，请重试。",
    "setup.done.title": "🎉 资料完成！",
    "setup.done.desc": "欢迎来到Migo ✈️",
    "setup.style.backpack": "背包旅行 🎒",
    "setup.style.luxury": "奢华旅行 ✈️",
    "setup.style.nature": "自然/徒步 🏔️",
    "setup.style.food": "美食之旅 🍜",
    "setup.style.culture": "文化/历史 🏛️",
    "setup.style.beach": "海滩/度假村 🏖️",
    "setup.style.photo": "摄影 📸",
    "setup.style.nightlife": "夜生活 🌙",
    "setup.style.shopping": "购物 🛍️",
    "setup.style.healing": "疗愈/瑜伽 🧘",
    "setup.style.local": "当地体验 🎭",
    "setup.style.drive": "自驾游 🚗",
    "setup.region.sea": "东南亚 🌴",
    "setup.region.europe": "欧洲 🏰",
    "setup.region.japan": "日本 🗾",
    "setup.region.usa": "美国/加拿大 🗽",
    "setup.region.latam": "拉丁美洲 🌎",
    "setup.region.oceania": "大洋洲 🦘",
    "setup.region.mideast": "中东/非洲 🌍",
    "setup.region.domestic": "国内旅行 🇰🇷",
    "setup.region.china": "中国/台湾 🐉",
    "setup.region.india": "印度 🕌",
    "setup.personality.planner": "计划型",
    "setup.personality.free": "自由灵魂",
    "setup.personality.social": "社交达人",
    "setup.personality.solo": "独行旅者",
    "setup.personality.photo": "摄影爱好者",
    "setup.personality.food": "美食探索者",
  },
  es: {
    "setup.step0.title": "Foto de perfil",
    "setup.step0.sub": "La primera impresión importa",
    "setup.step1.title": "Estilo de viaje",
    "setup.step1.sub": "¿Cómo viajas?",
    "setup.step2.title": "¿Qué tipo de viajero eres?",
    "setup.step2.sub": "Opcional",
    "setup.label.photo": "Foto de perfil",
    "setup.label.main": "Principal",
    "setup.label.add": "Añadir",
    "setup.type.traveler": "Viajero",
    "setup.type.local": "Guía local",
    "setup.label.nickname": "Apodo",
    "setup.placeholder.nickname": "ej. MigoTraveler",
    "setup.label.nationality": "Nacionalidad",
    "setup.label.selected": "Seleccionado",
    "setup.placeholder.searchCountry": "Buscar país...",
    "setup.label.bio": "Sobre mí",
    "setup.optional": "Opcional",
    "setup.placeholder.bio": "¿Qué tipo de viaje disfrutas? Preséntate brevemente ✈️",
    "setup.label.travelStyle": "Estilo de viaje",
    "setup.label.regions": "Destinos preferidos",
    "setup.multiSelect": "múltiple",
    "setup.label.personality": "Personalidad viajera",
    "setup.label.preview": "Vista previa",
    "setup.placeholder.noBio": "Sin presentación",
    "setup.btn.saving": "Guardando...",
    "setup.btn.complete": "Completar perfil",
    "setup.btn.next": "Siguiente",
    "setup.btn.mbtiNote": "La personalidad/MBTI se puede cambiar en cualquier momento 👌",
    "setup.validate.photo": "📸 Por favor añade al menos 1 foto",
    "setup.validate.nickname": "Por favor ingresa un apodo",
    "setup.validate.nationality": "Por favor selecciona tu nacionalidad",
    "setup.validate.style": "Por favor elige al menos 1 estilo de viaje",
    "setup.error.uploadFailed": "Error al subir la foto de perfil. Por favor verifica el formato de imagen o el estado de la red.",
    "setup.error.save": "Error al guardar",
    "setup.error.generic": "Ocurrió un error. Por favor inténtalo de nuevo.",
    "setup.done.title": "🎉 ¡Perfil completo!",
    "setup.done.desc": "Bienvenido a Migo ✈️",
    "setup.style.backpack": "Mochilero 🎒",
    "setup.style.luxury": "Lujo ✈️",
    "setup.style.nature": "Naturaleza/Senderismo 🏔️",
    "setup.style.food": "Tour gastronómico 🍜",
    "setup.style.culture": "Cultura/Historia 🏛️",
    "setup.style.beach": "Playa/Resort 🏖️",
    "setup.style.photo": "Fotografía 📸",
    "setup.style.nightlife": "Vida nocturna 🌙",
    "setup.style.shopping": "Compras 🛍️",
    "setup.style.healing": "Bienestar/Yoga 🧘",
    "setup.style.local": "Experiencia local 🎭",
    "setup.style.drive": "Viaje por carretera 🚗",
    "setup.region.sea": "Sudeste asiático 🌴",
    "setup.region.europe": "Europa 🏰",
    "setup.region.japan": "Japón 🗾",
    "setup.region.usa": "EE.UU./Canadá 🗽",
    "setup.region.latam": "América Latina 🌎",
    "setup.region.oceania": "Oceanía 🦘",
    "setup.region.mideast": "Oriente Medio/África 🌍",
    "setup.region.domestic": "Nacional 🇰🇷",
    "setup.region.china": "China/Taiwán 🐉",
    "setup.region.india": "India 🕌",
    "setup.personality.planner": "Planificador",
    "setup.personality.free": "Espíritu libre",
    "setup.personality.social": "Mariposa social",
    "setup.personality.solo": "Viajero solitario",
    "setup.personality.photo": "Coleccionista de fotos",
    "setup.personality.food": "Explorador gastronómico",
  },
  id: {
    "setup.step0.title": "Foto Profil",
    "setup.step0.sub": "Kesan pertama itu penting",
    "setup.step1.title": "Gaya Perjalanan",
    "setup.step1.sub": "Bagaimana cara Anda bepergian?",
    "setup.step2.title": "Tipe traveler seperti apa?",
    "setup.step2.sub": "Opsional",
    "setup.label.photo": "Foto Profil",
    "setup.label.main": "Utama",
    "setup.label.add": "Tambah",
    "setup.type.traveler": "Traveler",
    "setup.type.local": "Pemandu Lokal",
    "setup.label.nickname": "Nama panggilan",
    "setup.placeholder.nickname": "cth. MigoTraveler",
    "setup.label.nationality": "Kebangsaan",
    "setup.label.selected": "Dipilih",
    "setup.placeholder.searchCountry": "Cari negara...",
    "setup.label.bio": "Tentang Saya",
    "setup.optional": "Opsional",
    "setup.placeholder.bio": "Jenis perjalanan apa yang Anda sukai? Perkenalkan diri Anda secara singkat ✈️",
    "setup.label.travelStyle": "Gaya Perjalanan",
    "setup.label.regions": "Destinasi Favorit",
    "setup.multiSelect": "pilihan ganda",
    "setup.label.personality": "Kepribadian Perjalanan",
    "setup.label.preview": "Pratinjau",
    "setup.placeholder.noBio": "Belum ada perkenalan",
    "setup.btn.saving": "Menyimpan...",
    "setup.btn.complete": "Selesaikan Profil",
    "setup.btn.next": "Selanjutnya",
    "setup.btn.mbtiNote": "Kepribadian/MBTI bisa diubah kapan saja nanti 👌",
    "setup.validate.photo": "📸 Silakan tambahkan minimal 1 foto",
    "setup.validate.nickname": "Silakan masukkan nama panggilan",
    "setup.validate.nationality": "Silakan pilih kebangsaan Anda",
    "setup.validate.style": "Silakan pilih minimal 1 gaya perjalanan",
    "setup.error.uploadFailed": "Gagal mengunggah foto profil. Silakan periksa format file gambar atau status jaringan.",
    "setup.error.save": "Gagal menyimpan",
    "setup.error.generic": "Terjadi kesalahan. Silakan coba lagi.",
    "setup.done.title": "🎉 Profil selesai!",
    "setup.done.desc": "Selamat datang di Migo ✈️",
    "setup.style.backpack": "Backpacking 🎒",
    "setup.style.luxury": "Mewah ✈️",
    "setup.style.nature": "Alam/Hiking 🏔️",
    "setup.style.food": "Wisata Kuliner 🍜",
    "setup.style.culture": "Budaya/Sejarah 🏛️",
    "setup.style.beach": "Pantai/Resor 🏖️",
    "setup.style.photo": "Fotografi 📸",
    "setup.style.nightlife": "Kehidupan Malam 🌙",
    "setup.style.shopping": "Belanja 🛍️",
    "setup.style.healing": "Healing/Yoga 🧘",
    "setup.style.local": "Pengalaman Lokal 🎭",
    "setup.style.drive": "Road Trip 🚗",
    "setup.region.sea": "Asia Tenggara 🌴",
    "setup.region.europe": "Eropa 🏰",
    "setup.region.japan": "Jepang 🗾",
    "setup.region.usa": "AS/Kanada 🗽",
    "setup.region.latam": "Amerika Latin 🌎",
    "setup.region.oceania": "Oseania 🦘",
    "setup.region.mideast": "Timur Tengah/Afrika 🌍",
    "setup.region.domestic": "Domestik 🇰🇷",
    "setup.region.china": "Tiongkok/Taiwan 🐉",
    "setup.region.india": "India 🕌",
    "setup.personality.planner": "Perencana",
    "setup.personality.free": "Jiwa Bebas",
    "setup.personality.social": "Kupu-kupu Sosial",
    "setup.personality.solo": "Traveler Solo",
    "setup.personality.photo": "Kolektor Foto",
    "setup.personality.food": "Penjelajah Kuliner",
  },
  vi: {
    "setup.step0.title": "Ảnh đại diện",
    "setup.step0.sub": "Ấn tượng đầu tiên rất quan trọng",
    "setup.step1.title": "Phong cách du lịch",
    "setup.step1.sub": "Bạn du lịch như thế nào?",
    "setup.step2.title": "Bạn là kiểu du khách nào?",
    "setup.step2.sub": "Tùy chọn",
    "setup.label.photo": "Ảnh đại diện",
    "setup.label.main": "Chính",
    "setup.label.add": "Thêm",
    "setup.type.traveler": "Du khách",
    "setup.type.local": "Hướng dẫn viên địa phương",
    "setup.label.nickname": "Biệt danh",
    "setup.placeholder.nickname": "vd. MigoTraveler",
    "setup.label.nationality": "Quốc tịch",
    "setup.label.selected": "Đã chọn",
    "setup.placeholder.searchCountry": "Tìm quốc gia...",
    "setup.label.bio": "Giới thiệu bản thân",
    "setup.optional": "Tùy chọn",
    "setup.placeholder.bio": "Bạn thích kiểu du lịch nào? Hãy giới thiệu ngắn gọn về bản thân ✈️",
    "setup.label.travelStyle": "Phong cách du lịch",
    "setup.label.regions": "Điểm đến yêu thích",
    "setup.multiSelect": "chọn nhiều",
    "setup.label.personality": "Tính cách du lịch",
    "setup.label.preview": "Xem trước",
    "setup.placeholder.noBio": "Chưa có giới thiệu",
    "setup.btn.saving": "Đang lưu...",
    "setup.btn.complete": "Hoàn thành hồ sơ",
    "setup.btn.next": "Tiếp theo",
    "setup.btn.mbtiNote": "Tính cách/MBTI có thể thay đổi bất cứ lúc nào 👌",
    "setup.validate.photo": "📸 Vui lòng thêm ít nhất 1 ảnh",
    "setup.validate.nickname": "Vui lòng nhập biệt danh",
    "setup.validate.nationality": "Vui lòng chọn quốc tịch của bạn",
    "setup.validate.style": "Vui lòng chọn ít nhất 1 phong cách du lịch",
    "setup.error.uploadFailed": "Tải ảnh đại diện thất bại. Vui lòng kiểm tra định dạng ảnh hoặc trạng thái mạng.",
    "setup.error.save": "Lưu thất bại",
    "setup.error.generic": "Đã xảy ra lỗi. Vui lòng thử lại.",
    "setup.done.title": "🎉 Hồ sơ hoàn thành!",
    "setup.done.desc": "Chào mừng đến với Migo ✈️",
    "setup.style.backpack": "Ba lô 🎒",
    "setup.style.luxury": "Sang trọng ✈️",
    "setup.style.nature": "Thiên nhiên/Leo núi 🏔️",
    "setup.style.food": "Tour ẩm thực 🍜",
    "setup.style.culture": "Văn hóa/Lịch sử 🏛️",
    "setup.style.beach": "Biển/Resort 🏖️",
    "setup.style.photo": "Nhiếp ảnh 📸",
    "setup.style.nightlife": "Cuộc sống về đêm 🌙",
    "setup.style.shopping": "Mua sắm 🛍️",
    "setup.style.healing": "Chữa lành/Yoga 🧘",
    "setup.style.local": "Trải nghiệm địa phương 🎭",
    "setup.style.drive": "Đường trường 🚗",
    "setup.region.sea": "Đông Nam Á 🌴",
    "setup.region.europe": "Châu Âu 🏰",
    "setup.region.japan": "Nhật Bản 🗾",
    "setup.region.usa": "Mỹ/Canada 🗽",
    "setup.region.latam": "Mỹ Latinh 🌎",
    "setup.region.oceania": "Châu Đại Dương 🦘",
    "setup.region.mideast": "Trung Đông/Châu Phi 🌍",
    "setup.region.domestic": "Trong nước 🇰🇷",
    "setup.region.china": "Trung Quốc/Đài Loan 🐉",
    "setup.region.india": "Ấn Độ 🕌",
    "setup.personality.planner": "Người lên kế hoạch",
    "setup.personality.free": "Tâm hồn tự do",
    "setup.personality.social": "Bướm xã giao",
    "setup.personality.solo": "Du lịch một mình",
    "setup.personality.photo": "Người sưu tầm ảnh",
    "setup.personality.food": "Nhà thám hiểm ẩm thực",
  },
  th: {
    "setup.step0.title": "รูปโปรไฟล์",
    "setup.step0.sub": "ความประทับใจแรกสำคัญ",
    "setup.step1.title": "สไตล์การท่องเที่ยว",
    "setup.step1.sub": "คุณท่องเที่ยวแบบไหน?",
    "setup.step2.title": "คุณเป็นนักเดินทางแบบไหน?",
    "setup.step2.sub": "ไม่บังคับ",
    "setup.label.photo": "รูปโปรไฟล์",
    "setup.label.main": "หลัก",
    "setup.label.add": "เพิ่ม",
    "setup.type.traveler": "นักเดินทาง",
    "setup.type.local": "ไกด์ท้องถิ่น",
    "setup.label.nickname": "ชื่อเล่น",
    "setup.placeholder.nickname": "เช่น MigoTraveler",
    "setup.label.nationality": "สัญชาติ",
    "setup.label.selected": "เลือกแล้ว",
    "setup.placeholder.searchCountry": "ค้นหาประเทศ...",
    "setup.label.bio": "เกี่ยวกับฉัน",
    "setup.optional": "ไม่บังคับ",
    "setup.placeholder.bio": "คุณชอบการท่องเที่ยวแบบไหน? แนะนำตัวสั้นๆ ✈️",
    "setup.label.travelStyle": "สไตล์การท่องเที่ยว",
    "setup.label.regions": "จุดหมายที่ชอบ",
    "setup.multiSelect": "เลือกได้หลายรายการ",
    "setup.label.personality": "บุคลิกการเดินทาง",
    "setup.label.preview": "ดูตัวอย่าง",
    "setup.placeholder.noBio": "ไม่มีการแนะนำตัว",
    "setup.btn.saving": "กำลังบันทึก...",
    "setup.btn.complete": "โปรไฟล์สมบูรณ์",
    "setup.btn.next": "ถัดไป",
    "setup.btn.mbtiNote": "บุคลิกภาพ/MBTI สามารถเปลี่ยนได้ภายหลัง 👌",
    "setup.validate.photo": "📸 กรุณาเพิ่มรูปภาพอย่างน้อย 1 รูป",
    "setup.validate.nickname": "กรุณาใส่ชื่อเล่น",
    "setup.validate.nationality": "กรุณาเลือกสัญชาติของคุณ",
    "setup.validate.style": "กรุณาเลือกสไตล์การท่องเที่ยวอย่างน้อย 1 รายการ",
    "setup.error.uploadFailed": "อัปโหลดรูปโปรไฟล์ไม่สำเร็จ กรุณาตรวจสอบรูปแบบไฟล์ภาพหรือสถานะเครือข่าย",
    "setup.error.save": "บันทึกไม่สำเร็จ",
    "setup.error.generic": "เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง",
    "setup.done.title": "🎉 โปรไฟล์สมบูรณ์!",
    "setup.done.desc": "ยินดีต้อนรับสู่ Migo ✈️",
    "setup.style.backpack": "แบกเป้ 🎒",
    "setup.style.luxury": "หรูหรา ✈️",
    "setup.style.nature": "ธรรมชาติ/เดินป่า 🏔️",
    "setup.style.food": "ทัวร์อาหาร 🍜",
    "setup.style.culture": "วัฒนธรรม/ประวัติศาสตร์ 🏛️",
    "setup.style.beach": "ชายหาด/รีสอร์ท 🏖️",
    "setup.style.photo": "ถ่ายภาพ 📸",
    "setup.style.nightlife": "ไลฟ์กลางคืน 🌙",
    "setup.style.shopping": "ช้อปปิ้ง 🛍️",
    "setup.style.healing": "ฮีลลิ่ง/โยคะ 🧘",
    "setup.style.local": "ประสบการณ์ท้องถิ่น 🎭",
    "setup.style.drive": "ขับรถเที่ยว 🚗",
    "setup.region.sea": "เอเชียตะวันออกเฉียงใต้ 🌴",
    "setup.region.europe": "ยุโรป 🏰",
    "setup.region.japan": "ญี่ปุ่น 🗾",
    "setup.region.usa": "สหรัฐฯ/แคนาดา 🗽",
    "setup.region.latam": "ลาตินอเมริกา 🌎",
    "setup.region.oceania": "โอเชียเนีย 🦘",
    "setup.region.mideast": "ตะวันออกกลาง/แอฟริกา 🌍",
    "setup.region.domestic": "ในประเทศ 🇰🇷",
    "setup.region.china": "จีน/ไต้หวัน 🐉",
    "setup.region.india": "อินเดีย 🕌",
    "setup.personality.planner": "นักวางแผน",
    "setup.personality.free": "จิตวิญญาณอิสระ",
    "setup.personality.social": "ผีเสื้อสังคม",
    "setup.personality.solo": "นักเดินทางเดี่ยว",
    "setup.personality.photo": "นักสะสมภาพ",
    "setup.personality.food": "นักสำรวจอาหาร",
  },
  fr: {
    "setup.step0.title": "Photo de profil",
    "setup.step0.sub": "La première impression compte",
    "setup.step1.title": "Style de voyage",
    "setup.step1.sub": "Comment voyagez-vous ?",
    "setup.step2.title": "Quel type de voyageur ?",
    "setup.step2.sub": "Facultatif",
    "setup.label.photo": "Photo de profil",
    "setup.label.main": "Principale",
    "setup.label.add": "Ajouter",
    "setup.type.traveler": "Voyageur",
    "setup.type.local": "Guide local",
    "setup.label.nickname": "Pseudo",
    "setup.placeholder.nickname": "ex. MigoTraveler",
    "setup.label.nationality": "Nationalité",
    "setup.label.selected": "Sélectionné",
    "setup.placeholder.searchCountry": "Rechercher un pays...",
    "setup.label.bio": "À propos de moi",
    "setup.optional": "Facultatif",
    "setup.placeholder.bio": "Quel type de voyage aimez-vous ? Présentez-vous brièvement ✈️",
    "setup.label.travelStyle": "Style de voyage",
    "setup.label.regions": "Destinations préférées",
    "setup.multiSelect": "multiple",
    "setup.label.personality": "Personnalité de voyage",
    "setup.label.preview": "Aperçu",
    "setup.placeholder.noBio": "Pas de présentation",
    "setup.btn.saving": "Enregistrement...",
    "setup.btn.complete": "Compléter le profil",
    "setup.btn.next": "Suivant",
    "setup.btn.mbtiNote": "La personnalité/MBTI peut être modifié à tout moment 👌",
    "setup.validate.photo": "📸 Veuillez ajouter au moins 1 photo",
    "setup.validate.nickname": "Veuillez entrer un pseudo",
    "setup.validate.nationality": "Veuillez sélectionner votre nationalité",
    "setup.validate.style": "Veuillez choisir au moins 1 style de voyage",
    "setup.error.uploadFailed": "Échec du téléchargement de la photo de profil. Veuillez vérifier le format de l'image ou l'état du réseau.",
    "setup.error.save": "Échec de l'enregistrement",
    "setup.error.generic": "Une erreur est survenue. Veuillez réessayer.",
    "setup.done.title": "🎉 Profil complété !",
    "setup.done.desc": "Bienvenue sur Migo ✈️",
    "setup.style.backpack": "Sac à dos 🎒",
    "setup.style.luxury": "Luxe ✈️",
    "setup.style.nature": "Nature/Randonnée 🏔️",
    "setup.style.food": "Tour gastronomique 🍜",
    "setup.style.culture": "Culture/Histoire 🏛️",
    "setup.style.beach": "Plage/Station balnéaire 🏖️",
    "setup.style.photo": "Photographie 📸",
    "setup.style.nightlife": "Vie nocturne 🌙",
    "setup.style.shopping": "Shopping 🛍️",
    "setup.style.healing": "Bien-être/Yoga 🧘",
    "setup.style.local": "Expérience locale 🎭",
    "setup.style.drive": "Road trip 🚗",
    "setup.region.sea": "Asie du Sud-Est 🌴",
    "setup.region.europe": "Europe 🏰",
    "setup.region.japan": "Japon 🗾",
    "setup.region.usa": "États-Unis/Canada 🗽",
    "setup.region.latam": "Amérique latine 🌎",
    "setup.region.oceania": "Océanie 🦘",
    "setup.region.mideast": "Moyen-Orient/Afrique 🌍",
    "setup.region.domestic": "National 🇰🇷",
    "setup.region.china": "Chine/Taïwan 🐉",
    "setup.region.india": "Inde 🕌",
    "setup.personality.planner": "Planificateur",
    "setup.personality.free": "Esprit libre",
    "setup.personality.social": "Papillon social",
    "setup.personality.solo": "Voyageur solo",
    "setup.personality.photo": "Collectionneur de photos",
    "setup.personality.food": "Explorateur culinaire",
  },
  de: {
    "setup.step0.title": "Profilbild",
    "setup.step0.sub": "Der erste Eindruck zählt",
    "setup.step1.title": "Reisestil",
    "setup.step1.sub": "Wie reist du?",
    "setup.step2.title": "Was für ein Reisender bist du?",
    "setup.step2.sub": "Optional",
    "setup.label.photo": "Profilbild",
    "setup.label.main": "Haupt",
    "setup.label.add": "Hinzufügen",
    "setup.type.traveler": "Reisender",
    "setup.type.local": "Lokaler Reiseführer",
    "setup.label.nickname": "Spitzname",
    "setup.placeholder.nickname": "z.B. MigoTraveler",
    "setup.label.nationality": "Nationalität",
    "setup.label.selected": "Ausgewählt",
    "setup.placeholder.searchCountry": "Land suchen...",
    "setup.label.bio": "Über mich",
    "setup.optional": "Optional",
    "setup.placeholder.bio": "Welche Art von Reisen magst du? Stell dich kurz vor ✈️",
    "setup.label.travelStyle": "Reisestil",
    "setup.label.regions": "Bevorzugte Reiseziele",
    "setup.multiSelect": "Mehrfachauswahl",
    "setup.label.personality": "Reisepersönlichkeit",
    "setup.label.preview": "Vorschau",
    "setup.placeholder.noBio": "Keine Vorstellung",
    "setup.btn.saving": "Wird gespeichert...",
    "setup.btn.complete": "Profil vervollständigen",
    "setup.btn.next": "Weiter",
    "setup.btn.mbtiNote": "Persönlichkeit/MBTI kann jederzeit geändert werden 👌",
    "setup.validate.photo": "📸 Bitte füge mindestens 1 Foto hinzu",
    "setup.validate.nickname": "Bitte gib einen Spitznamen ein",
    "setup.validate.nationality": "Bitte wähle deine Nationalität",
    "setup.validate.style": "Bitte wähle mindestens 1 Reisestil",
    "setup.error.uploadFailed": "Profilbild-Upload fehlgeschlagen. Bitte überprüfe das Bildformat oder den Netzwerkstatus.",
    "setup.error.save": "Speichern fehlgeschlagen",
    "setup.error.generic": "Ein Fehler ist aufgetreten. Bitte versuche es erneut.",
    "setup.done.title": "🎉 Profil fertig!",
    "setup.done.desc": "Willkommen bei Migo ✈️",
    "setup.style.backpack": "Rucksackreisen 🎒",
    "setup.style.luxury": "Luxus ✈️",
    "setup.style.nature": "Natur/Wandern 🏔️",
    "setup.style.food": "Kulinarische Tour 🍜",
    "setup.style.culture": "Kultur/Geschichte 🏛️",
    "setup.style.beach": "Strand/Resort 🏖️",
    "setup.style.photo": "Fotografie 📸",
    "setup.style.nightlife": "Nachtleben 🌙",
    "setup.style.shopping": "Shopping 🛍️",
    "setup.style.healing": "Wellness/Yoga 🧘",
    "setup.style.local": "Lokale Erlebnisse 🎭",
    "setup.style.drive": "Roadtrip 🚗",
    "setup.region.sea": "Südostasien 🌴",
    "setup.region.europe": "Europa 🏰",
    "setup.region.japan": "Japan 🗾",
    "setup.region.usa": "USA/Kanada 🗽",
    "setup.region.latam": "Lateinamerika 🌎",
    "setup.region.oceania": "Ozeanien 🦘",
    "setup.region.mideast": "Naher Osten/Afrika 🌍",
    "setup.region.domestic": "Inland 🇰🇷",
    "setup.region.china": "China/Taiwan 🐉",
    "setup.region.india": "Indien 🕌",
    "setup.personality.planner": "Planer",
    "setup.personality.free": "Freigeist",
    "setup.personality.social": "Sozialer Schmetterling",
    "setup.personality.solo": "Solo-Reisender",
    "setup.personality.photo": "Fotosammler",
    "setup.personality.food": "Feinschmecker-Entdecker",
  },
  pt: {
    "setup.step0.title": "Foto de perfil",
    "setup.step0.sub": "A primeira impressão importa",
    "setup.step1.title": "Estilo de viagem",
    "setup.step1.sub": "Como você viaja?",
    "setup.step2.title": "Que tipo de viajante?",
    "setup.step2.sub": "Opcional",
    "setup.label.photo": "Foto de perfil",
    "setup.label.main": "Principal",
    "setup.label.add": "Adicionar",
    "setup.type.traveler": "Viajante",
    "setup.type.local": "Guia local",
    "setup.label.nickname": "Apelido",
    "setup.placeholder.nickname": "ex. MigoTraveler",
    "setup.label.nationality": "Nacionalidade",
    "setup.label.selected": "Selecionado",
    "setup.placeholder.searchCountry": "Pesquisar país...",
    "setup.label.bio": "Sobre mim",
    "setup.optional": "Opcional",
    "setup.placeholder.bio": "Que tipo de viagem você gosta? Apresente-se brevemente ✈️",
    "setup.label.travelStyle": "Estilo de viagem",
    "setup.label.regions": "Destinos preferidos",
    "setup.multiSelect": "múltipla",
    "setup.label.personality": "Personalidade de viagem",
    "setup.label.preview": "Pré-visualização",
    "setup.placeholder.noBio": "Sem apresentação",
    "setup.btn.saving": "Salvando...",
    "setup.btn.complete": "Completar perfil",
    "setup.btn.next": "Próximo",
    "setup.btn.mbtiNote": "Personalidade/MBTI pode ser alterado a qualquer momento 👌",
    "setup.validate.photo": "📸 Por favor adicione pelo menos 1 foto",
    "setup.validate.nickname": "Por favor insira um apelido",
    "setup.validate.nationality": "Por favor selecione sua nacionalidade",
    "setup.validate.style": "Por favor escolha pelo menos 1 estilo de viagem",
    "setup.error.uploadFailed": "Falha ao enviar foto de perfil. Por favor verifique o formato da imagem ou o status da rede.",
    "setup.error.save": "Falha ao salvar",
    "setup.error.generic": "Ocorreu um erro. Por favor tente novamente.",
    "setup.done.title": "🎉 Perfil completo!",
    "setup.done.desc": "Bem-vindo ao Migo ✈️",
    "setup.style.backpack": "Mochilão 🎒",
    "setup.style.luxury": "Luxo ✈️",
    "setup.style.nature": "Natureza/Trilhas 🏔️",
    "setup.style.food": "Tour gastronômico 🍜",
    "setup.style.culture": "Cultura/História 🏛️",
    "setup.style.beach": "Praia/Resort 🏖️",
    "setup.style.photo": "Fotografia 📸",
    "setup.style.nightlife": "Vida noturna 🌙",
    "setup.style.shopping": "Compras 🛍️",
    "setup.style.healing": "Bem-estar/Yoga 🧘",
    "setup.style.local": "Experiência local 🎭",
    "setup.style.drive": "Viagem de carro 🚗",
    "setup.region.sea": "Sudeste Asiático 🌴",
    "setup.region.europe": "Europa 🏰",
    "setup.region.japan": "Japão 🗾",
    "setup.region.usa": "EUA/Canadá 🗽",
    "setup.region.latam": "América Latina 🌎",
    "setup.region.oceania": "Oceania 🦘",
    "setup.region.mideast": "Oriente Médio/África 🌍",
    "setup.region.domestic": "Nacional 🇰🇷",
    "setup.region.china": "China/Taiwan 🐉",
    "setup.region.india": "Índia 🕌",
    "setup.personality.planner": "Planejador",
    "setup.personality.free": "Espírito livre",
    "setup.personality.social": "Borboleta social",
    "setup.personality.solo": "Viajante solo",
    "setup.personality.photo": "Colecionador de fotos",
    "setup.personality.food": "Explorador gastronômico",
  },
  ru: {
    "setup.step0.title": "Фото профиля",
    "setup.step0.sub": "Первое впечатление важно",
    "setup.step1.title": "Стиль путешествий",
    "setup.step1.sub": "Как вы путешествуете?",
    "setup.step2.title": "Какой вы путешественник?",
    "setup.step2.sub": "Необязательно",
    "setup.label.photo": "Фото профиля",
    "setup.label.main": "Главное",
    "setup.label.add": "Добавить",
    "setup.type.traveler": "Путешественник",
    "setup.type.local": "Местный гид",
    "setup.label.nickname": "Никнейм",
    "setup.placeholder.nickname": "напр. MigoTraveler",
    "setup.label.nationality": "Национальность",
    "setup.label.selected": "Выбрано",
    "setup.placeholder.searchCountry": "Поиск страны...",
    "setup.label.bio": "О себе",
    "setup.optional": "Необязательно",
    "setup.placeholder.bio": "Какой тип путешествий вам нравится? Коротко расскажите о себе ✈️",
    "setup.label.travelStyle": "Стиль путешествий",
    "setup.label.regions": "Предпочитаемые направления",
    "setup.multiSelect": "множественный выбор",
    "setup.label.personality": "Характер путешественника",
    "setup.label.preview": "Предпросмотр",
    "setup.placeholder.noBio": "Нет описания",
    "setup.btn.saving": "Сохранение...",
    "setup.btn.complete": "Завершить профиль",
    "setup.btn.next": "Далее",
    "setup.btn.mbtiNote": "Характер/MBTI можно изменить в любое время 👌",
    "setup.validate.photo": "📸 Пожалуйста, добавьте хотя бы 1 фото",
    "setup.validate.nickname": "Пожалуйста, введите никнейм",
    "setup.validate.nationality": "Пожалуйста, выберите вашу национальность",
    "setup.validate.style": "Пожалуйста, выберите хотя бы 1 стиль путешествий",
    "setup.error.uploadFailed": "Не удалось загрузить фото профиля. Проверьте формат файла или состояние сети.",
    "setup.error.save": "Ошибка сохранения",
    "setup.error.generic": "Произошла ошибка. Пожалуйста, попробуйте снова.",
    "setup.done.title": "🎉 Профиль готов!",
    "setup.done.desc": "Добро пожаловать в Migo ✈️",
    "setup.style.backpack": "Бэкпекинг 🎒",
    "setup.style.luxury": "Люкс ✈️",
    "setup.style.nature": "Природа/Хайкинг 🏔️",
    "setup.style.food": "Гастротур 🍜",
    "setup.style.culture": "Культура/История 🏛️",
    "setup.style.beach": "Пляж/Курорт 🏖️",
    "setup.style.photo": "Фотография 📸",
    "setup.style.nightlife": "Ночная жизнь 🌙",
    "setup.style.shopping": "Шопинг 🛍️",
    "setup.style.healing": "Оздоровление/Йога 🧘",
    "setup.style.local": "Местный опыт 🎭",
    "setup.style.drive": "Автопутешествие 🚗",
    "setup.region.sea": "Юго-Восточная Азия 🌴",
    "setup.region.europe": "Европа 🏰",
    "setup.region.japan": "Япония 🗾",
    "setup.region.usa": "США/Канада 🗽",
    "setup.region.latam": "Латинская Америка 🌎",
    "setup.region.oceania": "Океания 🦘",
    "setup.region.mideast": "Ближний Восток/Африка 🌍",
    "setup.region.domestic": "Внутренний туризм 🇰🇷",
    "setup.region.china": "Китай/Тайвань 🐉",
    "setup.region.india": "Индия 🕌",
    "setup.personality.planner": "Планировщик",
    "setup.personality.free": "Свободный дух",
    "setup.personality.social": "Социальная бабочка",
    "setup.personality.solo": "Соло-путешественник",
    "setup.personality.photo": "Фотоколлекционер",
    "setup.personality.food": "Гурман-исследователь",
  },
  ar: {
    "setup.step0.title": "صورة الملف الشخصي",
    "setup.step0.sub": "الانطباع الأول مهم",
    "setup.step1.title": "أسلوب السفر",
    "setup.step1.sub": "كيف تسافر؟",
    "setup.step2.title": "أي نوع من المسافرين أنت؟",
    "setup.step2.sub": "اختياري",
    "setup.label.photo": "صورة الملف الشخصي",
    "setup.label.main": "رئيسية",
    "setup.label.add": "إضافة",
    "setup.type.traveler": "مسافر",
    "setup.type.local": "مرشد محلي",
    "setup.label.nickname": "الاسم المستعار",
    "setup.placeholder.nickname": "مثال: MigoTraveler",
    "setup.label.nationality": "الجنسية",
    "setup.label.selected": "محدد",
    "setup.placeholder.searchCountry": "البحث عن بلد...",
    "setup.label.bio": "نبذة عني",
    "setup.optional": "اختياري",
    "setup.placeholder.bio": "ما نوع السفر الذي تستمتع به؟ عرّف بنفسك بإيجاز ✈️",
    "setup.label.travelStyle": "أسلوب السفر",
    "setup.label.regions": "الوجهات المفضلة",
    "setup.multiSelect": "اختيار متعدد",
    "setup.label.personality": "شخصية السفر",
    "setup.label.preview": "معاينة",
    "setup.placeholder.noBio": "لا يوجد تعريف",
    "setup.btn.saving": "جارٍ الحفظ...",
    "setup.btn.complete": "إكمال الملف الشخصي",
    "setup.btn.next": "التالي",
    "setup.btn.mbtiNote": "يمكن تغيير الشخصية/MBTI في أي وقت لاحقاً 👌",
    "setup.validate.photo": "📸 يرجى إضافة صورة واحدة على الأقل",
    "setup.validate.nickname": "يرجى إدخال اسم مستعار",
    "setup.validate.nationality": "يرجى اختيار جنسيتك",
    "setup.validate.style": "يرجى اختيار أسلوب سفر واحد على الأقل",
    "setup.error.uploadFailed": "فشل تحميل صورة الملف الشخصي. يرجى التحقق من تنسيق الصورة أو حالة الشبكة.",
    "setup.error.save": "فشل الحفظ",
    "setup.error.generic": "حدث خطأ. يرجى المحاولة مرة أخرى.",
    "setup.done.title": "🎉 الملف الشخصي مكتمل!",
    "setup.done.desc": "مرحباً بك في Migo ✈️",
    "setup.style.backpack": "حقيبة الظهر 🎒",
    "setup.style.luxury": "فاخر ✈️",
    "setup.style.nature": "طبيعة/مشي لمسافات 🏔️",
    "setup.style.food": "جولة طعام 🍜",
    "setup.style.culture": "ثقافة/تاريخ 🏛️",
    "setup.style.beach": "شاطئ/منتجع 🏖️",
    "setup.style.photo": "تصوير 📸",
    "setup.style.nightlife": "حياة ليلية 🌙",
    "setup.style.shopping": "تسوق 🛍️",
    "setup.style.healing": "استشفاء/يوغا 🧘",
    "setup.style.local": "تجربة محلية 🎭",
    "setup.style.drive": "رحلة بالسيارة 🚗",
    "setup.region.sea": "جنوب شرق آسيا 🌴",
    "setup.region.europe": "أوروبا 🏰",
    "setup.region.japan": "اليابان 🗾",
    "setup.region.usa": "الولايات المتحدة/كندا 🗽",
    "setup.region.latam": "أمريكا اللاتينية 🌎",
    "setup.region.oceania": "أوقيانوسيا 🦘",
    "setup.region.mideast": "الشرق الأوسط/أفريقيا 🌍",
    "setup.region.domestic": "محلي 🇰🇷",
    "setup.region.china": "الصين/تايوان 🐉",
    "setup.region.india": "الهند 🕌",
    "setup.personality.planner": "مخطط",
    "setup.personality.free": "روح حرة",
    "setup.personality.social": "فراشة اجتماعية",
    "setup.personality.solo": "مسافر منفرد",
    "setup.personality.photo": "جامع صور",
    "setup.personality.food": "مستكشف الطعام",
  },
  hi: {
    "setup.step0.title": "प्रोफ़ाइल फ़ोटो",
    "setup.step0.sub": "पहली छवि मायने रखती है",
    "setup.step1.title": "यात्रा शैली",
    "setup.step1.sub": "आप कैसे यात्रा करते हैं?",
    "setup.step2.title": "आप कैसे यात्री हैं?",
    "setup.step2.sub": "वैकल्पिक",
    "setup.label.photo": "प्रोफ़ाइल फ़ोटो",
    "setup.label.main": "मुख्य",
    "setup.label.add": "जोड़ें",
    "setup.type.traveler": "यात्री",
    "setup.type.local": "स्थानीय गाइड",
    "setup.label.nickname": "उपनाम",
    "setup.placeholder.nickname": "जैसे MigoTraveler",
    "setup.label.nationality": "राष्ट्रीयता",
    "setup.label.selected": "चयनित",
    "setup.placeholder.searchCountry": "देश खोजें...",
    "setup.label.bio": "मेरे बारे में",
    "setup.optional": "वैकल्पिक",
    "setup.placeholder.bio": "आपको किस तरह की यात्रा पसंद है? अपना संक्षिप्त परिचय दें ✈️",
    "setup.label.travelStyle": "यात्रा शैली",
    "setup.label.regions": "पसंदीदा गंतव्य",
    "setup.multiSelect": "एकाधिक चयन",
    "setup.label.personality": "यात्रा व्यक्तित्व",
    "setup.label.preview": "पूर्वावलोकन",
    "setup.placeholder.noBio": "कोई परिचय नहीं",
    "setup.btn.saving": "सहेजा जा रहा है...",
    "setup.btn.complete": "प्रोफ़ाइल पूर्ण करें",
    "setup.btn.next": "अगला",
    "setup.btn.mbtiNote": "व्यक्तित्व/MBTI को बाद में कभी भी बदला जा सकता है 👌",
    "setup.validate.photo": "📸 कृपया कम से कम 1 फ़ोटो जोड़ें",
    "setup.validate.nickname": "कृपया एक उपनाम दर्ज करें",
    "setup.validate.nationality": "कृपया अपनी राष्ट्रीयता चुनें",
    "setup.validate.style": "कृपया कम से कम 1 यात्रा शैली चुनें",
    "setup.error.uploadFailed": "प्रोफ़ाइल फ़ोटो अपलोड विफल। कृपया छवि फ़ाइल प्रारूप या नेटवर्क स्थिति जाँचें।",
    "setup.error.save": "सहेजना विफल",
    "setup.error.generic": "एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
    "setup.done.title": "🎉 प्रोफ़ाइल पूर्ण!",
    "setup.done.desc": "Migo में आपका स्वागत है ✈️",
    "setup.style.backpack": "बैकपैकिंग 🎒",
    "setup.style.luxury": "लक्ज़री ✈️",
    "setup.style.nature": "प्रकृति/हाइकिंग 🏔️",
    "setup.style.food": "फूड टूर 🍜",
    "setup.style.culture": "संस्कृति/इतिहास 🏛️",
    "setup.style.beach": "बीच/रिसॉर्ट 🏖️",
    "setup.style.photo": "फ़ोटोग्राफ़ी 📸",
    "setup.style.nightlife": "नाइटलाइफ़ 🌙",
    "setup.style.shopping": "शॉपिंग 🛍️",
    "setup.style.healing": "हीलिंग/योग 🧘",
    "setup.style.local": "स्थानीय अनुभव 🎭",
    "setup.style.drive": "रोड ट्रिप 🚗",
    "setup.region.sea": "दक्षिण-पूर्व एशिया 🌴",
    "setup.region.europe": "यूरोप 🏰",
    "setup.region.japan": "जापान 🗾",
    "setup.region.usa": "अमेरिका/कनाडा 🗽",
    "setup.region.latam": "लैटिन अमेरिका 🌎",
    "setup.region.oceania": "ओशिनिया 🦘",
    "setup.region.mideast": "मध्य पूर्व/अफ्रीका 🌍",
    "setup.region.domestic": "घरेलू 🇰🇷",
    "setup.region.china": "चीन/ताइवान 🐉",
    "setup.region.india": "भारत 🕌",
    "setup.personality.planner": "योजनाकार",
    "setup.personality.free": "स्वतंत्र आत्मा",
    "setup.personality.social": "सामाजिक तितली",
    "setup.personality.solo": "एकल यात्री",
    "setup.personality.photo": "फ़ोटो संग्राहक",
    "setup.personality.food": "खाने के शौकीन",
  },
  tr: {
    "setup.step0.title": "Profil Fotoğrafı",
    "setup.step0.sub": "İlk izlenim önemlidir",
    "setup.step1.title": "Seyahat Tarzı",
    "setup.step1.sub": "Nasıl seyahat ediyorsun?",
    "setup.step2.title": "Nasıl bir gezginsin?",
    "setup.step2.sub": "İsteğe bağlı",
    "setup.label.photo": "Profil Fotoğrafı",
    "setup.label.main": "Ana",
    "setup.label.add": "Ekle",
    "setup.type.traveler": "Gezgin",
    "setup.type.local": "Yerel Rehber",
    "setup.label.nickname": "Takma ad",
    "setup.placeholder.nickname": "örn. MigoTraveler",
    "setup.label.nationality": "Milliyet",
    "setup.label.selected": "Seçildi",
    "setup.placeholder.searchCountry": "Ülke ara...",
    "setup.label.bio": "Hakkımda",
    "setup.optional": "İsteğe bağlı",
    "setup.placeholder.bio": "Ne tür seyahatleri seviyorsun? Kısaca kendini tanıt ✈️",
    "setup.label.travelStyle": "Seyahat Tarzı",
    "setup.label.regions": "Tercih Edilen Destinasyonlar",
    "setup.multiSelect": "çoklu seçim",
    "setup.label.personality": "Seyahat Kişiliği",
    "setup.label.preview": "Önizleme",
    "setup.placeholder.noBio": "Tanıtım yok",
    "setup.btn.saving": "Kaydediliyor...",
    "setup.btn.complete": "Profili Tamamla",
    "setup.btn.next": "İleri",
    "setup.btn.mbtiNote": "Kişilik/MBTI daha sonra istediğin zaman değiştirilebilir 👌",
    "setup.validate.photo": "📸 Lütfen en az 1 fotoğraf ekleyin",
    "setup.validate.nickname": "Lütfen bir takma ad girin",
    "setup.validate.nationality": "Lütfen milliyetinizi seçin",
    "setup.validate.style": "Lütfen en az 1 seyahat tarzı seçin",
    "setup.error.uploadFailed": "Profil fotoğrafı yüklenemedi. Lütfen resim dosyası biçimini veya ağ durumunu kontrol edin.",
    "setup.error.save": "Kaydetme başarısız",
    "setup.error.generic": "Bir hata oluştu. Lütfen tekrar deneyin.",
    "setup.done.title": "🎉 Profil tamamlandı!",
    "setup.done.desc": "Migo'ya hoş geldiniz ✈️",
    "setup.style.backpack": "Sırt çantası 🎒",
    "setup.style.luxury": "Lüks ✈️",
    "setup.style.nature": "Doğa/Yürüyüş 🏔️",
    "setup.style.food": "Yemek Turu 🍜",
    "setup.style.culture": "Kültür/Tarih 🏛️",
    "setup.style.beach": "Plaj/Tatil köyü 🏖️",
    "setup.style.photo": "Fotoğrafçılık 📸",
    "setup.style.nightlife": "Gece hayatı 🌙",
    "setup.style.shopping": "Alışveriş 🛍️",
    "setup.style.healing": "Şifa/Yoga 🧘",
    "setup.style.local": "Yerel Deneyim 🎭",
    "setup.style.drive": "Karayolu Gezisi 🚗",
    "setup.region.sea": "Güneydoğu Asya 🌴",
    "setup.region.europe": "Avrupa 🏰",
    "setup.region.japan": "Japonya 🗾",
    "setup.region.usa": "ABD/Kanada 🗽",
    "setup.region.latam": "Latin Amerika 🌎",
    "setup.region.oceania": "Okyanusya 🦘",
    "setup.region.mideast": "Orta Doğu/Afrika 🌍",
    "setup.region.domestic": "Yurt içi 🇰🇷",
    "setup.region.china": "Çin/Tayvan 🐉",
    "setup.region.india": "Hindistan 🕌",
    "setup.personality.planner": "Planlayıcı",
    "setup.personality.free": "Özgür Ruh",
    "setup.personality.social": "Sosyal Kelebek",
    "setup.personality.solo": "Solo Gezgin",
    "setup.personality.photo": "Fotoğraf Koleksiyoncusu",
    "setup.personality.food": "Gurme Kaşif",
  },
  it: {
    "setup.step0.title": "Foto profilo",
    "setup.step0.sub": "La prima impressione conta",
    "setup.step1.title": "Stile di viaggio",
    "setup.step1.sub": "Come viaggi?",
    "setup.step2.title": "Che tipo di viaggiatore sei?",
    "setup.step2.sub": "Facoltativo",
    "setup.label.photo": "Foto profilo",
    "setup.label.main": "Principale",
    "setup.label.add": "Aggiungi",
    "setup.type.traveler": "Viaggiatore",
    "setup.type.local": "Guida locale",
    "setup.label.nickname": "Soprannome",
    "setup.placeholder.nickname": "es. MigoTraveler",
    "setup.label.nationality": "Nazionalità",
    "setup.label.selected": "Selezionato",
    "setup.placeholder.searchCountry": "Cerca paese...",
    "setup.label.bio": "Chi sono",
    "setup.optional": "Facoltativo",
    "setup.placeholder.bio": "Che tipo di viaggio ti piace? Presentati brevemente ✈️",
    "setup.label.travelStyle": "Stile di viaggio",
    "setup.label.regions": "Destinazioni preferite",
    "setup.multiSelect": "selezione multipla",
    "setup.label.personality": "Personalità di viaggio",
    "setup.label.preview": "Anteprima",
    "setup.placeholder.noBio": "Nessuna presentazione",
    "setup.btn.saving": "Salvataggio...",
    "setup.btn.complete": "Completa il profilo",
    "setup.btn.next": "Avanti",
    "setup.btn.mbtiNote": "Personalità/MBTI può essere cambiato in qualsiasi momento 👌",
    "setup.validate.photo": "📸 Per favore aggiungi almeno 1 foto",
    "setup.validate.nickname": "Per favore inserisci un soprannome",
    "setup.validate.nationality": "Per favore seleziona la tua nazionalità",
    "setup.validate.style": "Per favore scegli almeno 1 stile di viaggio",
    "setup.error.uploadFailed": "Caricamento foto profilo fallito. Controlla il formato dell'immagine o lo stato della rete.",
    "setup.error.save": "Salvataggio fallito",
    "setup.error.generic": "Si è verificato un errore. Per favore riprova.",
    "setup.done.title": "🎉 Profilo completato!",
    "setup.done.desc": "Benvenuto su Migo ✈️",
    "setup.style.backpack": "Zaino in spalla 🎒",
    "setup.style.luxury": "Lusso ✈️",
    "setup.style.nature": "Natura/Escursionismo 🏔️",
    "setup.style.food": "Tour gastronomico 🍜",
    "setup.style.culture": "Cultura/Storia 🏛️",
    "setup.style.beach": "Spiaggia/Resort 🏖️",
    "setup.style.photo": "Fotografia 📸",
    "setup.style.nightlife": "Vita notturna 🌙",
    "setup.style.shopping": "Shopping 🛍️",
    "setup.style.healing": "Benessere/Yoga 🧘",
    "setup.style.local": "Esperienza locale 🎭",
    "setup.style.drive": "Viaggio su strada 🚗",
    "setup.region.sea": "Sud-est asiatico 🌴",
    "setup.region.europe": "Europa 🏰",
    "setup.region.japan": "Giappone 🗾",
    "setup.region.usa": "USA/Canada 🗽",
    "setup.region.latam": "America Latina 🌎",
    "setup.region.oceania": "Oceania 🦘",
    "setup.region.mideast": "Medio Oriente/Africa 🌍",
    "setup.region.domestic": "Nazionale 🇰🇷",
    "setup.region.china": "Cina/Taiwan 🐉",
    "setup.region.india": "India 🕌",
    "setup.personality.planner": "Pianificatore",
    "setup.personality.free": "Spirito libero",
    "setup.personality.social": "Farfalla sociale",
    "setup.personality.solo": "Viaggiatore solitario",
    "setup.personality.photo": "Collezionista di foto",
    "setup.personality.food": "Esploratore gastronomico",
  },
};

// Helper: escape a string value for use in a JS double-quoted string literal
function escapeValue(v) {
  return v
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"');
}

// Build the insertion block for one language
function buildBlock(lang) {
  const entries = translations[lang];
  const lines = [];
  for (const [key, val] of Object.entries(entries)) {
    lines.push(`    "${key}": "${escapeValue(val)}",`);
  }
  return lines.join('\n');
}

// Read and patch the file
let content = readFileSync(FILE, 'utf8');

const languages = ['ko', 'en', 'ja', 'zh', 'es', 'id', 'vi', 'th', 'fr', 'de', 'pt', 'ru', 'ar', 'hi', 'tr', 'it'];

let patchCount = 0;

for (const lang of languages) {
  // We need to find `"setup.referral.valid": "..."` followed by a newline, INSIDE this language's section.
  // Strategy: find the language section marker, then find setup.referral.valid within it, then insert after that line.

  const langHeaderPattern = `"${lang}": {`;
  const langHeaderIdx = content.indexOf(langHeaderPattern);
  if (langHeaderIdx === -1) {
    console.error(`Could not find language section for: ${lang}`);
    continue;
  }

  // Check if setup.step0.title is already in this language section
  const step0Pattern = `"setup.step0.title"`;
  const nextLangHeaderIdx = content.indexOf(`\n  "`, langHeaderIdx + langHeaderPattern.length);
  const searchLimit = nextLangHeaderIdx === -1 ? content.length : nextLangHeaderIdx;
  const existingStep0Idx = content.indexOf(step0Pattern, langHeaderIdx);
  if (existingStep0Idx !== -1 && existingStep0Idx < searchLimit) {
    console.log(`ℹ️ Language ${lang} already has setup keys. Skipping...`);
    patchCount++;
    continue;
  }

  const marker = `"setup.referral.valid"`;
  const nextKey = `"profilePage.features.invite.label"`;

  // Find setup.referral.valid AFTER the language header
  const validIdx = content.indexOf(marker, langHeaderIdx);
  if (validIdx === -1) {
    console.error(`Could not find setup.referral.valid for: ${lang}`);
    continue;
  }

  // Find the end of this line (the newline after setup.referral.valid line)
  const lineEnd = content.indexOf('\n', validIdx);
  if (lineEnd === -1) {
    console.error(`Could not find line end for setup.referral.valid in: ${lang}`);
    continue;
  }

  // Verify the next non-empty line contains profilePage.features.invite.label
  const nextLineStart = lineEnd + 1;
  const nextLineContent = content.substring(nextLineStart, content.indexOf('\n', nextLineStart));
  if (!nextLineContent.includes(nextKey)) {
    console.error(`Expected ${nextKey} after setup.referral.valid in ${lang}, but found: ${nextLineContent.trim()}`);
    continue;
  }

  // Build the insertion block
  const block = buildBlock(lang);

  // Insert after the setup.referral.valid line
  content = content.substring(0, lineEnd + 1) + block + '\n' + content.substring(lineEnd + 1);
  patchCount++;
  console.log(`✅ Patched ${lang} (${Object.keys(translations[lang]).length} keys)`);
}

if (patchCount === languages.length) {
  writeFileSync(FILE, content, 'utf8');
  console.log(`\n🎉 Successfully patched all ${patchCount} languages!`);
} else {
  console.error(`\n❌ Only patched ${patchCount}/${languages.length} languages. File NOT saved.`);
  process.exit(1);
}
